import { expect, test } from "@playwright/test"

test("public pages share mobile navigation and close it after navigation", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/ru")
  const toggle = page.locator(".site-menu-toggle")
  await expect(toggle).toBeVisible()
  await expect(page.locator("header.site-header")).toHaveCount(1)
  await expect(page.locator("footer")).toHaveCount(1)
  await expect(page.locator('.public-site-menu > a[href="/ru/features"]')).toHaveCount(0)
  await toggle.click()
  await expect(toggle).toHaveAttribute("aria-expanded", "true")
  await page.locator('.public-site-menu > a[href="/ru/about"]').click()
  await expect(page).toHaveURL(/\/ru\/about$/)
  await expect(toggle).toHaveAttribute("aria-expanded", "false")
  await expect(page.locator("header.site-header")).toHaveCount(1)
  await expect(page.locator("footer")).toHaveCount(1)
  await toggle.click()
  await page.keyboard.press("Escape")
  await expect(toggle).toHaveAttribute("aria-expanded", "false")
  await expect(toggle).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test("documentation has a working theme control in the mobile header", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/ru/docs/installation")
  const toggle = page.locator('#nd-subnav button[title*="тем"]')
  await expect(toggle).toBeVisible()
  const before = await page.locator("html").getAttribute("class")
  await toggle.click()
  await expect(page.locator("html")).not.toHaveAttribute("class", before ?? "")
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
