import {roles,closingFeature} from './landing-composition.mjs'
export const roleLayouts=[{id:'open',name:'Three open lists'},{id:'rail',name:'Side-by-side role chooser'},{id:'folds',name:'Expandable role rows'}]
export const outcomeLayouts=[{id:'simple',name:'Simple outcomes'},{id:'dialogue',name:'Short conversations'},{id:'lines',name:'Ask → get rows'}]
export const conversationLayouts=[{id:'compact',name:'Compact bubbles'},{id:'plain',name:'Open agent response'},{id:'flow',name:'Continuous conversation'}]
export const landingVariants=[
 {id:'landing-editorial',name:'Open and compact',role:'open',outcome:'simple',conversation:'compact',description:'All three uses visible together. Short outcome examples and compact chat bubbles.'},
 {id:'landing-workspace',name:'Focused workspace',role:'rail',outcome:'dialogue',conversation:'plain',description:'A quiet role chooser beside the capabilities. Conversation examples and an open agent reply.'},
 {id:'landing-folds',name:'Expandable overview',role:'folds',outcome:'lines',conversation:'flow',description:'Three expandable role rows. Direct request-to-result examples and a continuous conversation.'},
]
const labels={personal:'Personal account',bot:'Bots',admin:'Administer groups'}
const lead={personal:'Catch up, remember agreements and prepare replies in your own conversations.',bot:'Answer customers and share updates through your bot’s own identity.',admin:'Find unanswered questions, collect decisions and review moderation.'}
const featureList=r=>`<dl class="role5-features">${r.items.map(([t,d])=>`<div><dt>${t}</dt><dd>${d}</dd></div>`).join('')}</dl>`
export function roleBlock5(layout,prefix,{icon,link,docs}){
 const head=`<div class="section-heading5"><h2>Take control of your messaging.</h2><p>For your own conversations, your bots and the groups you run.</p></div>`
 const guides=r=>`<div class="role5-links">${link('See it in action',`/examples?case=${r.scenario}`)}${link('Read the guide',`${docs}/${r.guide}`)}</div>`
 if(layout==='open')return `<section class="wrap section roles5 roles5-open">${head}<div class="role5-columns">${roles.map(r=>`<article><h3>${icon[r.icon]}${labels[r.id]}</h3><p>${lead[r.id]}</p><dl class="role5-features">${r.items.slice(0,3).map(([t,d])=>`<div><dt>${t}</dt><dd>${d}</dd></div>`).join('')}</dl><details class="role5-more"><summary>3 more capabilities${icon.down}</summary>${featureList({...r,items:r.items.slice(3)})}</details>${guides(r)}</article>`).join('')}</div></section>`
 if(layout==='folds')return `<section class="wrap section roles5 roles5-folds">${head}<div class="role5-folds">${roles.map((r,i)=>`<details ${!i?'open':''}><summary><span>${icon[r.icon]}<b>${labels[r.id]}</b></span><span>${lead[r.id]}</span>${icon.down}</summary><div class="role5-fold-body">${featureList(r)}${guides(r)}</div></details>`).join('')}</div></section>`
 return `<section class="wrap section roles5 roles5-rail">${head}<div class="role5-workspace"><div class="role5-selector" role="tablist" aria-orientation="vertical" aria-label="Choose an account type">${roles.map((r,i)=>`<button type="button" role="tab" id="${prefix}-role-${r.id}" aria-controls="${prefix}-role-panel-${r.id}" aria-selected="${!i}" tabindex="${i?-1:0}" data-audience-tab="${r.id}">${icon[r.icon]}<span><b>${labels[r.id]}</b><small>${lead[r.id]}</small></span>${icon.arrow}</button>`).join('')}</div><div class="role5-panels">${roles.map((r,i)=>`<div role="tabpanel" id="${prefix}-role-panel-${r.id}" aria-labelledby="${prefix}-role-${r.id}" data-audience-panel ${i?'hidden':''}>${featureList(r)}${guides(r)}</div>`).join('')}</div></div></section>`
}
const outcomes=[
 {title:'Find an old agreement',icon:'search',ask:'Where did we agree to meet?',answer:'The place and time, with the original messages and any later changes.',scenario:'search'},
 {title:'Prepare for a conversation',icon:'note',ask:'What should I know before the call?',answer:'A short brief of the decisions, blockers and questions still open.',scenario:'context'},
 {title:'Draft a reply with full context',icon:'reply',ask:'Help me answer their latest question.',answer:'A draft that takes earlier answers, changed plans and your promises into account.',scenario:'commitments'},
]
export function outcomeBlock5(layout,{icon,link}){
 const head='<div class="section-heading5"><h2>What you can do</h2><p>Give your agent the question. Get an answer grounded in your messages.</p></div>'
 if(layout==='lines')return `<section class="wrap section outcomes5 outcomes5-lines">${head}<div class="outcome5-lines">${outcomes.map(o=>`<article><h3>${icon[o.icon]}${o.title}</h3><blockquote>“${o.ask}”</blockquote><div><p>${o.answer}</p>${link('See the conversation',`/examples?case=${o.scenario}`)}</div></article>`).join('')}</div></section>`
 return `<section class="${layout==='simple'?'section':'wrap section'} outcomes5 outcomes5-${layout}">${layout==='simple'?'<div class="wrap">':''}${head}<div class="outcome5-columns">${outcomes.map(o=>`<article><h3>${icon[o.icon]}${o.title}</h3>${layout==='dialogue'?`<div class="outcome5-exchange"><blockquote>“${o.ask}”</blockquote><p>${o.answer}</p></div>`:`<blockquote>“${o.ask}”</blockquote><p>${o.answer}</p>`}${link('See the conversation',`/examples?case=${o.scenario}`)}</article>`).join('')}</div>${layout==='simple'?'</div>':''}</section>`
}
export function trustBlock5({icon,link,docs}){
 const puzzle='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 4H4v5a3 3 0 1 0 0 6v5h5a3 3 0 1 1 6 0h5v-6a3 3 0 1 0 0-6V4h-5a3 3 0 1 0-6 0Z"/></svg>'
 const data='<svg viewBox="0 0 24 24" aria-hidden="true"><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 4 16 4 16 0V5M4 12c0 4 16 4 16 0"/></svg>'
 return `<section class="trust5"><div class="wrap trust5-grid"><h2 class="sr-only">Open source, your data and your agent</h2><article>${icon.github}<div><h3>Open source</h3><p>Both messaging tools are free under the MIT licence. Read the code, report an issue or contribute.</p><div class="trust5-links"><a href="https://github.com/leemour/tg-cli" class="text-link">${icon.github}tg · Source code${icon.arrow}</a><a href="https://github.com/leemour/max-cli" class="text-link">${icon.github}max · Source code${icon.arrow}</a></div></div></article><article>${data}<div><h3>Your data</h3><p>Your messaging archive stays on your computer. You choose the accounts and permissions. Content passed to your agent follows its model settings.</p>${link('Security guide',`${docs}/security`)}</div></article><article>${puzzle}<div><h3>Your agent</h3><p>Use Claude Code, Codex, Cursor, Gemini CLI, Hermes or another agent that works with CLI tools or MCP.</p>${link('Agent setup guide',`${docs}/agents`)}</div></article></div></section>`
}
export function closingFeature5(kind,prefix,args){
 if(kind!=='search')return closingFeature(kind,prefix,args)
 const {icon,link,docs}=args
 return `<div class="starter feature-panel search5"><h3>Search by topic, person and date.</h3><p>Combine conditions to find the message you need across your saved chats.</p><div class="query5-preview"><code>Atlas AND (invoice OR budget)<br>AND has:file</code>${icon.search}</div><details class="query5-try"><summary>Try a query on sample messages${icon.down}</summary><div data-mini-search><div class="query-presets" role="group" aria-label="Sample search queries"><button type="button" data-search-preset="Atlas AND (invoice OR budget) AND has:file" aria-pressed="true">Topic + files</button><button type="button" data-search-preset='from:Alice AND date:[2026-10-03 TO 2026-10-04]' aria-pressed="false">Person + date</button></div><label class="sr-only" for="${prefix}-mini-query">Search the sample messages</label><textarea id="${prefix}-mini-query" data-mini-query rows="2" spellcheck="false">Atlas AND (invoice OR budget) AND has:file</textarea><div class="mini-search-status" data-mini-status role="status" aria-live="polite"></div><div class="mini-search-results" data-mini-results></div><p class="feature-caption">36 fictional messages · local demo</p></div></details>${link('Explore the search playground',`${docs}/search-playground`)}</div>`
}
