export const homepageRefinements=[
 {id:'home-access',name:'Inset commands + access controls',commandStyle:'soft',closing:'access',description:'A green command strip with a checkmark. The closing panel explains read-only and confirmed-change profiles.'},
 {id:'home-connect',name:'Compact console + connection paths',commandStyle:'console',closing:'connections',description:'A small terminal surface for commands. The closing panel shows CLI skills and MCP as two connection paths.'},
 {id:'home-notes',name:'Checked command list + useful notes',commandStyle:'ledger',closing:'notes',description:'A white outlined command list. The closing panel shows how a conversation can become a Markdown project note.'},
]
export function closingPanel(mode,{icon,link,docs}){
 if(mode==='connections')return `<div class="starter closing-panel closing-connections"><h3>Use the agent you already have</h3><p>Choose the connection that fits how you use it.</p><div class="connection-path"><b>Agent in your terminal</b><p>Install the CLI and its skill so your agent can use the commands.</p>${link('Connect through a skill',`${docs}/agents`)}</div><div class="connection-path"><b>Agent in a desktop app</b><p>Connect the messaging tools through an MCP server.</p>${link('Connect through MCP',`${docs}/mcp`)}</div></div>`
 if(mode==='notes')return `<div class="starter closing-panel closing-notes"><h3>Keep the useful part in your notes</h3><p>Ask your agent to turn an agreed plan into a Markdown note.</p><div class="note-preview"><span>${icon.note}<b>Atlas / Next steps.md</b></span><ul><li>Get the final copy to Anna by Thursday.</li><li>Give Tom production access for the remaining check.</li><li>Keep Friday’s launch under review until both are done.</li></ul></div><p class="closing-caption">Messages provide the context. Your agent writes the note in Obsidian or another Markdown editor.</p>${link('See where the context came from','/examples?case=context')}</div>`
 return `<div class="starter closing-panel closing-access"><h3>Choose what your agent can do</h3><p>Your profile can read messages, or ask you before making changes.</p><div class="access-options" role="tablist" aria-label="Explore access modes"><button type="button" role="tab" id="access-read-${mode}" aria-controls="access-read-panel-${mode}" aria-selected="true" tabindex="0" data-access-tab="read">Read only</button><button type="button" role="tab" id="access-confirm-${mode}" aria-controls="access-confirm-panel-${mode}" aria-selected="false" tabindex="-1" data-access-tab="confirm">Confirm changes</button></div><div id="access-read-panel-${mode}" role="tabpanel" aria-labelledby="access-read-${mode}" data-access-panel="read"><ul><li>Read and search the chats you choose.</li><li>Prepare summaries and drafts in your agent.</li><li>Block message sends and other changes.</li></ul></div><div id="access-confirm-panel-${mode}" role="tabpanel" aria-labelledby="access-confirm-${mode}" data-access-panel="confirm" hidden><ul><li>Read and search your conversations.</li><li>Ask before sends and other changes.</li><li>Limit which chats may receive messages.</li></ul></div>${link('Configure a profile’s permissions',`${docs}/security`)}</div>`
}
export function refinementNav(link){return `<nav class="wrap refinement-nav" aria-label="Compare homepage refinements">${link('Compare blocks and command styles','/refinement-options')}${homepageRefinements.map(v=>`<a href="/${v.id}">${v.name.split(' + ')[0]}</a>`).join('')}${link('Compact feature layouts','/features-compact')}</nav>`}
