const studio=document.querySelector('[data-studio]')
if(studio){
 const frame=studio.querySelector('[data-studio-frame]'),viewport=studio.querySelector('[data-studio-viewport]'),what=studio.querySelector('[data-studio-what]'),closing=studio.querySelector('[data-studio-closing]'),theme=studio.querySelector('[data-studio-theme]'),width=studio.querySelector('[data-studio-width]'),archive=studio.querySelector('[data-studio-archive]'),icons=studio.querySelector('[data-studio-icons]')
 const fit=()=>{const target=Number(width.value);const scale=Math.min(1,Math.max(1,viewport.clientWidth-2)/target);frame.style.width=`${target}px`;frame.style.height=`${Math.max(450,viewport.clientHeight/scale)}px`;frame.style.transform=`scale(${scale})`}
 const update=()=>{const route=archive.value||`/landing-${what.value}-${closing.value}`;const url=new URL(route,location.origin);if(!archive.value){url.searchParams.set('theme',theme.value);url.searchParams.set('icons',icons.checked?'1':'0')}frame.src=url.href;frame.title=archive.value?archive.selectedOptions[0].textContent:`${what.selectedOptions[0].textContent} · ${closing.selectedOptions[0].textContent}`;studio.querySelector('[data-studio-open]').href=url.href;studio.querySelector('[data-studio-copy]').dataset.copy=url.href;studio.querySelector('[data-studio-status]').textContent=frame.title;fit()}
 for(const select of [what,closing])select.addEventListener('change',()=>{archive.value='';update()});for(const select of [theme,width,archive,icons])select.addEventListener('change',update);new ResizeObserver(fit).observe(viewport);frame.addEventListener('load',fit);update()
}
const filter=document.querySelector('[data-design-filter]');if(filter)filter.addEventListener('input',()=>{const term=filter.value.trim().toLowerCase();const entries=Array.from(document.querySelectorAll('[data-design-entry]'));entries.forEach(e=>e.hidden=!e.dataset.search.includes(term));document.querySelectorAll('[data-design-group]').forEach(g=>g.hidden=!Array.from(g.querySelectorAll('[data-design-entry]')).some(e=>!e.hidden));document.querySelector('[data-design-empty]').hidden=entries.some(e=>!e.hidden)})
const blockFilter=document.querySelector('[data-block-filter]');if(blockFilter){const filter=()=>document.querySelectorAll('[data-block-group]').forEach(block=>block.hidden=blockFilter.value!=='all'&&block.dataset.blockGroup!==blockFilter.value);blockFilter.addEventListener('change',filter);const requested=new URL(location.href).searchParams.get('group');if(Array.from(blockFilter.options).some(o=>o.value===requested))blockFilter.value=requested;filter()}
const blockTheme=document.querySelector('[data-block-theme]');if(blockTheme)blockTheme.addEventListener('change',()=>document.querySelectorAll('[data-block-src]').forEach(frame=>frame.src=`${frame.dataset.blockSrc}?theme=${blockTheme.value}`))

for(const frame of document.querySelectorAll('[data-block-src]')){
 let observer
 frame.addEventListener('load',()=>{observer?.disconnect();try{const main=frame.contentDocument.querySelector('main');if(!main)return;const dark=blockTheme?.value==='dark';frame.contentDocument.documentElement.classList.toggle('dark',dark);frame.contentDocument.documentElement.classList.toggle('light',!dark);const fit=()=>frame.style.height=`${Math.max(180,Math.min(1800,Math.ceil(main.getBoundingClientRect().height+24)))}px`;observer=new ResizeObserver(fit);observer.observe(main);fit()}catch{}})
}
