import { mkdir, writeFile } from "node:fs/promises"
import { wirecatLogoSvg } from "../../lib/brand.ts"

const root = new URL("./", import.meta.url)
const docs = "https://wirecat.dev/en/docs"
const arrow = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>'
const icons = {
  telegram: '<path d="m3 11 18-7-5 17-5-6-4 3 1-6 10-6-8 8Z"/>',
  max: '<path d="M5 6h14v11h-8l-5 4V6Z"/><path d="m9 13 2-3 2 3 2-3"/>',
  email: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',
  notes: '<path d="M6 3h9l4 4v14H6Z"/><path d="M14 3v5h5M9 12h7M9 16h5"/>',
  search: '<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',
  agent: '<path d="M9 4v4H5v8h4v4h6v-4h4V8h-4V4Z"/><path d="M9 12h6"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  copy: '<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V4H4v12h4"/>',
  shield: '<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',
  moon: '<path d="M20 15.5A8.5 8.5 0 0 1 8.5 4a8.5 8.5 0 1 0 11.5 11.5Z"/>',
}
const icon = (name) => `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]}</svg>`
const link = (label, href, cls = "text-link") => `<a class="${cls}" href="${href}">${label}${arrow}</a>`
const examples = [
  {
    id: "recall", tab: "Find a recommendation", ask: "Who recommended an accountant for freelancers? What did they say?", heading: "The recommendation, with the reason", result: "<p><strong>Anna recommended Elena Ruiz.</strong> She works with freelancers and helps with quarterly filings.</p><p>Your note says you need English-language support. Elena’s email confirms she offers it.</p>", next: "You have the contact and enough context to decide whether to reach out.", artifact: "<strong>Contact to consider</strong><p>Elena Ruiz · @elena_accounts</p><p>Freelancers · quarterly filings · English support</p>",
    sources: [
      ["telegram", "Telegram", "Freelance friends · Anna", "Elena handles my quarterly filings. She works with freelancers. Try @elena_accounts."],
      ["email", "Email", "Elena · via Himalaya", "Yes, I work with self-employed clients and can handle your filings in English."],
      ["notes", "Obsidian", "Admin / Find an accountant.md", "Need someone who works with freelancers and can explain the process in English."],
    ],
    command: 'tg messages search "accountant" --context 2',
  },
  {
    id: "brief", tab: "Catch up on what matters", ask: "What needs my attention today? Check my messages, email and project notes.", heading: "Three things worth your attention", result: "<ul><li><strong>Review Nora’s draft</strong> before the team call.</li><li><strong>Check the delivery change:</strong> the supplier now expects Thursday morning.</li><li><strong>Residents meeting:</strong> Thursday at 19:00.</li></ul>", next: "Your project note says to verify delivery before confirming the date to the customer.", artifact: "<strong>Next step</strong><p>Confirm the supplier’s revised date, then update the customer with the checked information.</p>",
    sources: [
      ["telegram", "Telegram", "Team · Nora", "The first draft is ready. Could you review it before our call?"],
      ["max", "MAX", "Residents group", "The annual residents meeting is Thursday at 19:00."],
      ["email", "Email", "Supplier · via Himalaya", "The shipment is now expected Thursday morning. Please confirm the delivery address."],
      ["notes", "Obsidian", "Projects / Delivery.md", "Verify the supplier’s date before confirming it to the customer."],
    ],
    command: "tg inbox --json",
  },
  {
    id: "reply", tab: "Follow up with context", ask: "Check where the brochure stands and draft the right follow-up to Maria.", heading: "A reply that picks up the thread", result: "<p>Maria already sent the first design. She is waiting for the photos, which the photographer expects to share tonight.</p><blockquote>Thanks for the first design, Maria. The photographer expects to send the photos tonight. I’ll forward them when they arrive. Could we review the final layout tomorrow?</blockquote>", next: "Review the draft, then ask your agent to send it through your account.", artifact: "<strong>Draft ready for review</strong><p>Acknowledge what arrived. Resolve what is missing. Agree on the next step.</p>",
    sources: [
      ["telegram", "Telegram", "Maria · project chat", "First brochure design attached. I’m still waiting for the approved photos."],
      ["email", "Email", "Photographer · via Himalaya", "The edited photos are ready. I expect to share them tonight."],
      ["notes", "Obsidian", "Projects / Brochure brief.md", "Use the approved photos. Review the final layout with Maria before sending to print."],
    ],
    command: 'tg messages list "Maria" --limit 20',
  },
  {
    id: "notes", tab: "Turn a discussion into a note", ask: "Bring the workshop plans together in my Obsidian note. Keep the open questions and sources.", heading: "A project note you can build on", result: "<p>Your agent can turn the discussion into a proposed note update, keeping agreements and unanswered questions separate.</p>", next: "Review the update before asking your agent to save it in your vault.", artifact: "<strong>Workshop / Plan.md</strong><ul><li>Saturday workshop agreed</li><li>Mara leads the morning session</li><li>Venue capacity: 24</li></ul><p><b>Still open:</b> who brings the projector?</p><p class=\"artifact-source\">Sources: team chat, volunteer group, venue email</p>",
    sources: [
      ["telegram", "Telegram", "Workshop team", "Saturday works. Mara will lead the morning session."],
      ["max", "MAX", "Volunteers", "Who can bring a projector? We haven’t assigned that yet."],
      ["email", "Email", "Venue · via Himalaya", "Your booking is confirmed. The room has capacity for 24 people."],
      ["notes", "Obsidian", "Workshop / Plan.md", "Collect the agreed plan and keep unresolved questions visible."],
    ],
    command: 'tg review --chat "Workshop team" --since-time 7d',
  },
]
const pages = [
  { id: "guided", name: "Memory → useful action", heading: "Memory for your messages.<br><em>Context for your agent.</em>", description: "WireCat connects your AI agent to conversations, email and notes. Find what you need, bring the backstory together and turn it into a useful next step.", first: "recall", layout: "guided", pitch: "A guided request, source messages and a useful answer. Starts with the everyday pain of forgetting where something was said." },
  { id: "workspace", name: "Your agent’s workspace", heading: "Your agent, with<br><em>the context you live in.</em>", description: "Messages in one place. Email in another. Notes somewhere else. Give your agent the tools to find the relevant pieces and help you move forward.", first: "brief", layout: "workspace", pitch: "A compact introduction beside a working example. Starts with a briefing and lets the visitor try four useful tasks." },
  { id: "connections", name: "From scattered to useful", heading: "Bring the scattered<br><em>pieces together.</em>", description: "Find decisions, reconnect conversations and turn discussion into a reply or a note. WireCat helps the agent you already use work across your messaging and knowledge tools.", first: "notes", layout: "connections", pitch: "A source-to-context-to-action composition. Starts with a note built from messages and email, then exposes the evidence." },
]

const shell = (p) => `<nav class="preview-nav" aria-label="Local design comparison"><a href="/">New homepages</a><div>${pages.map(x => `<a href="/${x.id}" ${x.id === p?.id ? 'aria-current="page"' : ""}>${x.name}</a>`).join("")}</div><a href="/references">Original designs</a></nav><header class="wrap site-header"><a class="brand" href="/" aria-label="WireCat homepage previews">${wirecatLogoSvg}</a><nav aria-label="Site"><a href="#features">What you can do</a><a href="#integrations">Connections</a><a href="${docs}">Docs</a><button class="theme-switch" aria-label="Switch to dark theme">${icon("moon")}</button>${link("Connect your agent", "#connect", "button small")}</nav></header>`
const connectors = () => `<div class="connector-list" aria-label="Available tools and integrations"><span>${icon("telegram")}Telegram</span><span>${icon("max")}MAX</span><span>${icon("email")}Email</span><span>${icon("notes")}Obsidian</span></div>`
const heroCopy = (p) => `<div class="hero-copy"><h1>${p.heading}</h1><p class="lede">${p.description}</p><div class="hero-actions">${link("Connect your agent", "#connect", "button")}${link("Explore the examples", "#example")}</div>${connectors()}<p class="micro">Free, open-source tools. Use your existing AI agent.</p></div>`
const sourceCard = (s, index, mode = "") => `<details class="source-card ${s[0]} ${mode}"><summary><span class="source-icon">${icon(s[0])}</span><span><b>${s[1]}</b><small>${s[2]}</small><span class="source-excerpt">${s[3]}</span></span>${icon("search")}</summary><div class="source-detail"><span>Original source · example ${index + 1}</span><blockquote>${s[3]}</blockquote></div></details>`
const tabs = (id, active) => `<div class="example-tabs" role="tablist" aria-label="Choose a workflow">${examples.map(e => `<button type="button" role="tab" id="${id}-tab-${e.id}" aria-controls="${id}-panel-${e.id}" aria-selected="${e.id === active}" tabindex="${e.id === active ? 0 : -1}" data-example="${e.id}">${e.tab}</button>`).join("")}</div>`
const ask = (e) => `<div class="ask"><span class="ask-icon">${icon("agent")}</span><p>${e.ask}</p><button class="icon-button" data-copy="${e.ask}" aria-label="Copy this request" title="Copy request">${icon("copy")}</button></div>`
const answer = (e, artifact = false) => `<div class="answer"><div class="answer-heading">${icon("check")}<h3>${e.heading}</h3></div>${e.result}<p class="next-step">${e.next}</p>${artifact ? `<div class="artifact">${e.artifact}</div>` : ""}<details class="reasoning"><summary>Where the answer comes from</summary><p>Your configured agent retrieves the relevant material with WireCat and your connected tools, then interprets it. Open the source items to inspect the text behind this example.</p><code>${e.command}</code><p>Email uses Himalaya; notes use your Obsidian vault. Configure the connections you want your agent to use.</p></details></div>`

function guided(p) {
  return `<div class="example guided-demo" id="example"><h2 class="sr-only">Follow a question from sources to answer</h2>${tabs(p.id, p.first)}${examples.map(e => `<div class="example-panel guided-steps" id="${p.id}-panel-${e.id}" role="tabpanel" aria-labelledby="${p.id}-tab-${e.id}" ${e.id !== p.first ? "hidden" : ""}><div class="guided-ask"><h3><span class="step">1</span>Ask your agent</h3><p class="step-note">Use your own words.</p>${ask(e)}<div class="guide-line" aria-hidden="true">${arrow}</div><p class="question-payoff">Find the thing you remember.<br>Recover the details you don’t.</p></div><div class="guided-sources"><h3><span class="step">2</span>Gather the context</h3><p class="step-note">Open an item to inspect its source.</p>${e.sources.map((s, i) => sourceCard(s, i)).join("")}</div><div class="guided-answer"><h3><span class="step">3</span>Use what you find</h3><p class="step-note">An answer, a draft or a note.</p>${answer(e)}</div></div>`).join("")}<p class="example-caption">Illustrative workflow · WireCat supplies tools; your agent supplies the reasoning.</p></div>`
}
function workspace(p) {
  return `<div class="example workbench" id="example"><h2 class="sr-only">Your agent working with your information</h2><div class="workbench-title"><span class="terminal-dots" aria-hidden="true"><i></i><i></i><i></i></span><span>Your agent · connected context</span><span class="workbench-status">Example workflow</span></div>${tabs(p.id, p.first)}${examples.map(e => `<div class="example-panel" id="${p.id}-panel-${e.id}" role="tabpanel" aria-labelledby="${p.id}-tab-${e.id}" ${e.id !== p.first ? "hidden" : ""}>${ask(e)}<div class="workspace-content"><div class="workspace-sources"><h3>Relevant source material</h3>${e.sources.map((s, i) => sourceCard(s, i, "result-row")).join("")}</div>${answer(e)}</div></div>`).join("")}<div class="workbench-footer"><span>Original sources stay inspectable</span><span>Telegram · MAX · Email · Notes</span></div></div>`
}
function connections(p) {
  return `<div class="example connection-demo" id="example"><h2 class="sr-only">Bring sources together into a useful result</h2>${tabs(p.id, p.first)}${examples.map(e => `<div class="example-panel" id="${p.id}-panel-${e.id}" role="tabpanel" aria-labelledby="${p.id}-tab-${e.id}" ${e.id !== p.first ? "hidden" : ""}>${ask(e)}<div class="connection-flow"><div class="map-sources"><h3>The pieces you already have</h3>${e.sources.map((s, i) => sourceCard(s, i)).join("")}</div><div class="map-context"><div class="map-arrow" aria-hidden="true">${arrow}</div><div class="context-node">${icon("agent")}<h3>Your agent brings<br>the context together</h3><p>Finds the relevant material, checks the history and separates agreements from open questions.</p><span>${e.sources.length} source items in this example</span></div><div class="map-arrow" aria-hidden="true">${arrow}</div></div><div class="map-output"><h3>A useful result</h3><div class="artifact output-artifact">${e.artifact}</div><p class="next-step">${e.next}</p><details class="reasoning"><summary>What connects these pieces?</summary>${e.result}<p>Your agent gathers the sources you have configured. Review the original material before saving the note or sending a reply.</p></details></div></div></div>`).join("")}<p class="example-caption">Illustrative workflow · Open the sources, or switch to another task.</p></div>`
}

const features = (id) => `<section class="wrap section features" id="features"><div class="section-title"><h2>${id === "guided" ? "Remember more. Repeat less. Move things forward." : id === "workspace" ? "Useful work, from the information you already have" : "The context is useful when you can act on it"}</h2><p>Search is the start. Your agent can use what it finds to help you decide, reply and keep your knowledge current.</p></div><div class="feature-columns"><article>${icon("search")}<h3>Find what you can’t quite remember</h3><p>Recover a recommendation, decision or file. Search stored messages by words, or set up conversation search by meaning.</p><button data-jump-example="recall" class="text-link">See a recommendation${arrow}</button></article><article>${icon("agent")}<h3>Get the backstory before you reply</h3><p>Bring earlier messages, changed plans and relevant notes together. Draft the follow-up that fits what happened.</p><button data-jump-example="reply" class="text-link">See a contextual reply${arrow}</button></article><article>${icon("notes")}<h3>Turn a discussion into something lasting</h3><p>Prepare a brief or an Obsidian note with the decisions, open questions and source references you want to keep.</p><button data-jump-example="notes" class="text-link">See a proposed note${arrow}</button></article></div></section>`
const audiences = () => `<section class="audience-band"><div class="wrap audience-row"><h2>For your conversations.<br>And the ones you run.</h2><article><h3>Your own account</h3><p>Catch up, recover the history, prepare replies and schedule messages.</p>${link("Personal account guide", `${docs}/tg/usage`)}</article><article><h3>Your bots</h3><p>Give your agent a messaging channel for customer answers, updates and files.</p>${link("Bot workflows", `${docs}/bot-api`)}</article><article><h3>Your communities</h3><p>Review unanswered questions, summarize decisions and preview moderation.</p>${link("Group administration", `${docs}/tg/groups`)}</article></div></section>`
const integrations = () => `<section class="wrap section integrations" id="integrations"><div><h2>Start with your messages.<br>Bring more of your world.</h2><p>Telegram and MAX are WireCat’s first messaging tools. Email and Obsidian already fit into the workflow. More messenger connections are part of where we’re going.</p><p class="project-definition">WireCat is a free, open-source project for connecting your AI agent to conversations and knowledge.</p></div><div class="integration-table"><a href="${docs}/tg"><span>${icon("telegram")}Telegram</span><p>WireCat’s tg CLI · your account and bots</p>${arrow}</a><a href="${docs}/max"><span>${icon("max")}MAX</span><p>WireCat’s max CLI · your account and bots</p>${arrow}</a><a href="https://github.com/pimalaya/himalaya"><span>${icon("email")}Email</span><p>Through the third-party Himalaya CLI</p>${arrow}</a><a href="https://obsidian.md"><span>${icon("notes")}Obsidian</span><p>Your existing vault, used by your agent</p>${arrow}</a><details><summary>How do these tools work together?</summary><p>Your agent coordinates the tools you have configured. WireCat retrieves and acts on messaging data; Himalaya handles email; your agent reads or edits notes in your vault. Setup varies by workflow.</p><p>Semantic conversation retrieval currently searches built and embedded conversations within one account. Bringing other sources into an answer is a separate agent workflow.</p></details></div></section>`
const trust = () => `<section class="wrap trust"><article>${icon("shield")}<div><h3>Your access, configured by you</h3><p>Choose read-only profiles, allowed actions or confirmation before changes.</p>${link("Access and permissions", `${docs}/security`)}</div></article><article>${icon("notes")}<div><h3>Sources you can inspect</h3><p>Ask for the underlying messages and notes. Check the evidence behind the answer.</p>${link("Try a first task", `${docs}/first-tasks`)}</div></article><article>${icon("agent")}<div><h3>Your agent, your workflow</h3><p>Use CLI skills or MCP with a compatible agent. The tools are open source.</p>${link("Connect your agent", `${docs}/agents`)}</div></article></section>`
const setup = () => `<section class="wrap section setup" id="connect"><div><h2>Give your agent somewhere useful to start.</h2><p>Connect Telegram or MAX, then ask one real question about your conversations. Add email and notes when you want a broader workflow.</p><div class="setup-actions">${link("Telegram setup", `${docs}/installation#tg`, "button")}${link("MAX setup", `${docs}/installation#max`, "button secondary")}</div><p class="micro">The tools are free. Your agent and model may have their own costs. The guides cover installation, sign-in and agent connections.</p></div><div class="starter"><div class="install-tabs" role="group" aria-label="Choose a messenger"><button data-provider="tg" aria-pressed="true">Telegram</button><button data-provider="max" aria-pressed="false">MAX</button></div><div class="command"><code id="install-command">npm i -g @wirecat/tg-cli</code><button id="copy-install" data-copy="npm i -g @wirecat/tg-cli" aria-label="Copy installation command">${icon("copy")}</button></div><h3>Then ask your agent</h3><p>“Find a decision from last week and show me the messages behind it.”</p><details><summary>Where is my information processed?</summary><p>The messaging archive is stored on your computer. Content you give your agent follows that agent’s local or cloud model configuration. Email and notes keep their own storage and access settings.</p></details></div></section>`
const footer = () => `<footer class="wrap footer"><a class="brand" href="/" aria-label="WireCat previews">${wirecatLogoSvg}</a><p>Open-source tools for conversations and knowledge.</p><div><a href="/references">Three original design mockups</a><a href="http://127.0.0.1:4325/">Earlier six homepages</a><a href="https://wirecat.dev/en/about">About the project</a></div></footer><div class="toast" role="status" aria-live="polite"></div>`

const wallpaper = `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400" fill="none" stroke="#dce5e0" stroke-width="1.4" stroke-linejoin="round"><g transform="translate(50 55) rotate(-14) scale(.7)"><path d="M0 0l36-14-10 34-8-12zM18 8l18-22"/></g><g transform="translate(300 280) rotate(12) scale(.8)"><path d="M-22 8c0-12 12-18 26-16 12 2 18 8 18 16zM-18 -2l-2-9 7 5M-10 -7l3-7 3 8M22 8c5 0 7-6 2-9"/></g></svg>`
await writeFile(new URL("wallpaper.svg", root), wallpaper)
const document = (title, content, cls = "") => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${title} · WireCat new homepage</title><link rel="icon" href="/icon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><script src="/interactions.js" defer></script></head><body class="${cls}"><a class="skip" href="#main">Skip to content</a>${content}</body></html>`
for (const p of pages) {
  const demo = p.layout === "guided" ? guided(p) : p.layout === "workspace" ? workspace(p) : connections(p)
  await writeFile(new URL(`${p.id}.html`, root), document(p.name, `${shell(p)}<main id="main"><section class="hero wrap ${p.layout}-hero">${heroCopy(p)}${demo}</section>${features(p.id)}${audiences()}${integrations()}${trust()}${setup()}</main>${footer()}`, `page-${p.id}`))
}
const home = `<header class="wrap site-header"><a class="brand" href="/" aria-label="WireCat">${wirecatLogoSvg}</a><a href="/references">Preserved original designs</a></header><main class="wrap gallery" id="main"><h1>A broader offer.<br><em>Three new homepages.</em></h1><p class="lede">Built from the compact designs you liked. Each shows messages, email and notes becoming something useful through your own AI agent.</p><div class="gallery-grid">${pages.map(p => `<article><a href="/${p.id}" class="preview-window"><img src="/previews/${p.id}.png" alt="${p.name} homepage preview" width="1440" height="1000"></a><h2>${p.name}</h2><p>${p.pitch}</p>${link("Open this homepage", `/${p.id}`)}</article>`).join("")}</div><div class="archive-links"><h2>Keep comparing</h2><p>The originals are preserved alongside these new pages.</p>${link("The three designs from port 38999", "/references")}${link("The earlier six-page exploration", "http://127.0.0.1:4325/")}</div></main>${footer()}`
await writeFile(new URL("index.html", root), document("Three new approaches", home, "gallery-page"))
const references = `<header class="wrap site-header"><a class="brand" href="/" aria-label="WireCat">${wirecatLogoSvg}</a>${link("New homepages", "/")}</header><main class="wrap reference-gallery" id="main"><h1>The three designs<br><em>you liked.</em></h1><p class="lede">Preserved copies of the original visual mockups from port 38999. These images keep their original content; the new implemented pages explore revised content separately.</p>${[["guided-task", "Guided task", "/guided"], ["product-in-action", "Product in action", "/workspace"], ["conversation-map", "Conversation map", "/connections"]].map(([id, name, href]) => `<section><div class="reference-title"><h2>${name}</h2>${link("See its new direction", href)}</div><a href="/references/${id}.png"><img src="/references/${id}.png" alt="Original ${name} WireCat visual mockup" width="1536" height="1024"></a></section>`).join("")}</main>${footer()}`
await writeFile(new URL("references.html", root), document("Preserved original mockups", references))
await mkdir(new URL("previews/", root), { recursive: true })
console.log("Built three new homepages, comparison page and preserved-reference page.")
