import { mkdir, writeFile } from "node:fs/promises"

const root = new URL("./", import.meta.url)
const variants = [
  { id: "direct", name: "Put your agent to work", angle: "A concrete Telegram + MAX offer", description: "Product first. A reply demonstration, three useful outcomes, then the three audience paths.", headline: "Put your AI agent to work in <em>Telegram and MAX.</em>", lede: "Search your conversations, gather context and send replies through the agent you already use.", proof: "Free, open-source CLI tools. Works with Claude Code, Codex and MCP clients." },
  { id: "memory", name: "Memory for your messengers", angle: "Remember, reconnect, follow through", description: "Memory first. Searchable conversations and source evidence lead; actions follow naturally.", headline: "Memory for<br><em>your messengers.</em>", lede: "The recommendation you forgot. The decision buried in a group. The promise from last week. Give your AI agent a way back to all of it in Telegram and MAX.", proof: "A searchable local archive, connected to your own AI agent." },
  { id: "context", name: "The context to act", angle: "Evidence → understanding → action", description: "Outcome first. A project brief turns scattered messages into a decision and a contextual reply.", headline: "Go into every conversation with <em>the context at hand.</em>", lede: "Connect your agent to Telegram and MAX. Bring decisions, open questions and commitments together before you reply.", proof: "Your conversations. Your choice of agent. Free and open source." },
  { id: "audiences", name: "Your account, bots and groups", angle: "Three equal paths from the first screen", description: "Audience first. Personal, bot and group-admin uses are visible immediately, with a demo for each.", headline: "Your conversations.<br>Your bots.<br><em>Your communities.</em>", lede: "Put your AI agent to work across Telegram and MAX. Find context, help customers and keep your groups useful.", proof: "Two open-source CLI tools. Three ways to put them to work." },
  { id: "workflow", name: "Bring the pieces together", angle: "Messages + email + notes", description: "Workflow first. A meeting-preparation sequence connects messaging with Himalaya email and Obsidian notes.", headline: "The conversation is bigger<br><em>than one chat.</em>", lede: "Start with Telegram and MAX. Bring email and Obsidian notes into the same agent workflow, so scattered information can become a useful next step.", proof: "WireCat’s tg and max tools, alongside Himalaya and Obsidian." },
  { id: "minimal", name: "Just ask", angle: "A short, focused route to the first answer", description: "A concise page. One clear promise, three examples, a little proof and a direct setup path.", headline: "Your chats have answers.<br><em>Just ask.</em>", lede: "Connect the AI agent you already use to Telegram and MAX. Find what was said, gather the context and send a reply.", proof: "Free and open source. Runs on your computer." },
]

const arrow = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>'
const logo = '<svg viewBox="0 0 32 32" aria-hidden="true"><circle cx="16" cy="16" r="16" fill="#544af4"/><path d="M9 21V11l4 4 3-4 3 4 4-4v10" fill="none" stroke="#fff" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg><span>WireCat</span>'
const docs = "https://wirecat.dev/en/docs"
const link = (label, href, cls = "text-link") => `<a class="${cls}" href="${href}">${label}${arrow}</a>`
const button = (label = "Connect your agent") => link(label, "#connect", "button")
const header = (v) => `<nav class="review-bar" aria-label="Homepage preview navigation"><a href="/">All six approaches</a><label for="variant">Compare <select id="variant" aria-label="Homepage approach">${variants.map(x => `<option value="${x.id}" ${x.id === v.id ? "selected" : ""}>${x.name}</option>`).join("")}</select></label><span class="review-note">Local design preview</span></nav><header class="site-header wrap"><a class="brand" href="/" aria-label="WireCat preview collection">${logo}</a><nav aria-label="Main navigation"><a href="#uses">What you can do</a><a href="${docs}">Docs</a><button class="theme-toggle" aria-label="Switch to dark theme" title="Switch theme"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 15.5A8.5 8.5 0 0 1 8.5 4a8.5 8.5 0 1 0 11.5 11.5Z"/></svg></button>${link("Connect", "#connect", "button small")}</nav></header>`
const intro = (v, extra = "") => `<div class="hero-copy"><h1>${v.headline}</h1><p class="lede">${v.lede}</p><div class="hero-actions">${button()}${extra}</div><p class="micro">${v.proof}</p></div>`

const cases = {
  find: { title: "Find something you forgot", prompt: "Who recommended an accountant who works with freelancers?", heading: "The recommendation was Elena", answer: "<p><strong>Anna recommended Elena Ruiz</strong> in Freelance friends. She mentioned that Elena handles quarterly filings for freelancers.</p><p>The contact Anna shared: <strong>@elena_accounts</strong>.</p>", source: "Anna · Freelance friends", quote: "Elena handles my quarterly filings. She works with freelancers. Try @elena_accounts.", code: 'tg conversations search "accountant for freelancers"', action: "Find the recommendation, with the conversation around it." },
  brief: { title: "Gather context for a call", prompt: "Prepare me for the Atlas call. What changed, and what still needs a decision?", heading: "You can start with the decisions", answer: "<dl class=\"brief-list\"><div><dt>Agreed</dt><dd>Launch on Friday. Final copy is due Thursday.</dd></div><div><dt>Changed</dt><dd>Tom sent the first payment-flow results. Two cases still need testing.</dd></div><div><dt>Open</dt><dd>Who provides staging access for the remaining tests?</dd></div></dl>", source: "Anna + Tom · Atlas team and project DMs", quote: "Anna: We’re launching Friday. I need the copy Thursday. Tom: First test results are attached. I still need access for the remaining two cases.", code: 'tg review --chat "Atlas team" --since-time 7d', action: "A usable meeting brief, assembled from relevant conversations." },
  reply: { title: "Reply with the history in mind", prompt: "Check what Tom has already sent and draft the right follow-up.", heading: "A follow-up that reflects what happened", answer: "<p>Tom already sent the first results, so a reminder to send everything would miss the context.</p><blockquote>Thanks for the first results, Tom. I’ll arrange staging access for the two remaining cases. Could you finish those before Thursday?</blockquote><p class=\"draft-status\">Draft ready for your review</p>", source: "Tom · Project DM", quote: "First results are attached. The remaining two cases are blocked on staging access.", code: 'tg messages list "Tom" --limit 20', action: "Read the history, prepare the reply, then decide what to send." },
  bot: { title: "Help a customer", prompt: "Check the customer’s question and draft a reply using our delivery policy.", heading: "An answer grounded in your own information", answer: "<p><strong>Customer:</strong> Can my order arrive before Friday?</p><blockquote>Our standard delivery takes 3–5 working days. Send me your order number and I can help check its current status.</blockquote><p class=\"draft-status\">Uses the policy you supplied; asks for the missing order details.</p>", source: "Customer message + supplied delivery policy", quote: "Customer: Can my order arrive before Friday? Policy: Standard delivery takes 3–5 working days. Delivery dates require an order-status check.", code: "tg bot messages list", action: "Your agent supplies the reasoning; your bot supplies the messaging channel." },
  admin: { title: "Run a useful group", prompt: "What questions still need an answer in our residents group?", heading: "Three questions need an admin’s attention", answer: "<dl class=\"brief-list\"><div><dt>Parking</dt><dd>Is the permit renewal deadline still Friday?</dd></div><div><dt>Repairs</dt><dd>Who can approve the lift repair quote?</dd></div><div><dt>Meeting</dt><dd>Can members join next week’s meeting remotely?</dd></div></dl><p class=\"draft-status\">A review of open questions, ready to check against the source messages.</p>", source: "Residents · recent group messages", quote: "Maya: Is the parking deadline still Friday? Ben: Who approves the lift quote? Ana: Will there be a remote link for the meeting?", code: 'tg review --chat "Residents" --unanswered', action: "Put the unanswered questions in front of the person who can resolve them." },
}

function demo(keys = ["find", "brief", "reply"], active = keys[0], compact = false) {
  return `<section class="demo ${compact ? "compact" : ""}" aria-label="Agent workflow demonstration"><h2 class="sr-only">Agent conversation example</h2><div class="demo-top"><span class="agent-label"><span class="live-dot"></span>Your agent · Telegram + MAX</span><span>Interactive example</span></div><div class="demo-tabs" role="tablist" aria-label="Choose an example">${keys.map(k => `<button role="tab" id="tab-${k}" aria-controls="panel-${k}" aria-selected="${k === active}" tabindex="${k === active ? 0 : -1}" data-case="${k}">${cases[k].title}</button>`).join("")}</div>${keys.map(k => `<div class="demo-panel" id="panel-${k}" role="tabpanel" aria-labelledby="tab-${k}" ${k !== active ? "hidden" : ""}><div class="prompt"><p>${cases[k].prompt}</p><button class="copy-prompt" data-copy="${cases[k].prompt}" aria-label="Copy this request" title="Copy request"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V4H4v12h4"/></svg></button></div><div class="answer"><h3>${cases[k].heading}</h3>${cases[k].answer}<details class="sources"><summary>Inspect the source messages</summary><p class="source-name">${cases[k].source}</p><blockquote>${cases[k].quote}</blockquote></details><details class="execution"><summary>How the tools help</summary><p>${cases[k].action}</p><code>${cases[k].code}</code><p>WireCat retrieves messages and provides actions. Your configured agent interprets them.</p></details></div></div>`).join("")}<div class="demo-bottom">The request, the context, a useful result.</div></section>`
}

const outcomes = (title = "Find it. Understand it. Follow through.") => `<section class="section wrap" id="uses"><h2>${title}</h2><div class="outcome-columns"><article><h3>Find what was said</h3><p>Recover a decision, a recommendation or a document from your stored conversations.</p></article><article><h3>Bring the context together</h3><p>Ask your agent to assemble the relevant history, open questions and agreements.</p></article><article><h3>Do something with it</h3><p>Prepare a reply, send a file, follow up or manage a group through your agent.</p></article></div></section>`

const segmentData = [
  { name: "Your conversations", key: "brief", text: "Pick up the thread with the context at hand.", points: ["Find decisions and recommendations", "Review commitments and open questions", "Prepare replies and scheduled messages"], href: `${docs}/tg/usage` },
  { name: "Your bots", key: "bot", text: "Help people with the information you provide.", points: ["Draft answers from your knowledge base", "Send relevant updates and files", "Handle buttons and customer requests"], href: `${docs}/bot-api` },
  { name: "Your communities", key: "admin", text: "Know what needs an admin’s attention.", points: ["Review unanswered questions", "Summarize decisions and discussions", "Preview moderation by your rules"], href: `${docs}/tg/groups` },
]
const segments = (interactive = false) => `<section class="section wrap segments" ${interactive ? 'id="uses"' : ""}><div class="section-intro"><h2>${interactive ? "What would you like your agent to handle?" : "Your account, your bots, your groups"}</h2><p>The same tools, used in different ways. Start with the conversations that matter to you.</p></div><div class="segment-columns">${segmentData.map(s => `<article><h3>${s.name}</h3><p class="segment-promise">${s.text}</p><ul>${s.points.map(p => `<li>${p}</li>`).join("")}</ul>${interactive ? `<button class="text-link segment-select" data-show-case="${s.key}">See this example${arrow}</button>` : link("Explore the guide", s.href)}</article>`).join("")}</div></section>`

const trust = () => `<section class="trust-section"><div class="wrap trust-grid"><h2>Your tools.<br>Your choices.</h2><div><h3>A local archive you can use</h3><p>Keep selected chat history on your computer. Search stored messages offline and return to the original sources.</p></div><div><h3>The agent you already know</h3><p>Use a terminal agent with CLI skills, or connect a compatible client through MCP.</p></div><div><h3>Permissions you can configure</h3><p>Choose read-only access, confirmation before changes or allowed actions for your profile.</p></div></div><p class="wrap trust-note">Your archive is local. Content supplied to your agent follows that agent’s local or cloud model configuration. ${link("Storage and access", `${docs}/security`)}</p></section>`

const extension = (short = false) => `<section class="section wrap extension"><div><h2>${short ? "Beyond the chat" : "Bring email and notes into the conversation"}</h2><p>Your agent can work alongside Himalaya for email and your Obsidian notes. Gather the messages, check the email and update the project note in one workflow.</p>${link("See the connected-workflow approach", "/workflow")}</div><div class="recipe"><span>Telegram + MAX</span><p>What did we agree?</p><span>Email through Himalaya</span><p>What changed since then?</p><span>Obsidian</span><p>Keep the project note current.</p></div></section>`

const setup = (heading = "Give your agent its first conversation") => `<section class="section wrap connect" id="connect"><div><h2>${heading}</h2><p>Install tg or max, sign in to your account, then connect the agent you already use.</p><p class="micro">Free tools, open source. Your existing agent or model may have its own costs.</p><div class="setup-links">${link("Agent setup guide", `${docs}/agents`)}${link("Read the source", "https://github.com/WireCatLabs/tg-cli")}</div></div><div class="installation"><div class="messenger-tabs" role="group" aria-label="Choose the tool to install"><button data-install="tg" aria-pressed="true">Telegram</button><button data-install="max" aria-pressed="false">MAX</button></div><p class="install-description">tg connects your Telegram account to your terminal and agent.</p><div class="command"><code id="install-command">npm i -g @leemour/tg-cli</code><button id="copy-install" data-copy="npm i -g @leemour/tg-cli">Copy</button></div><a class="text-link install-guide" href="${docs}/installation#tg">Installation and sign-in guide${arrow}</a><div class="first-request"><span>Then ask your agent</span><p>“Find the latest decision about our project and show me the source messages.”</p></div><p class="micro">The tools run on Windows, macOS and Linux. See the guide for runtime requirements and authentication.</p></div></section>`

const faq = () => `<section class="section wrap faq"><h2>A few useful details</h2><div><details><summary>Do I need to switch AI agents?</summary><p>No. WireCat provides CLI tools, skills and MCP connections for compatible agents. Use the setup guide for your client.</p></details><details><summary>Can I start with my own account?</summary><p>Yes. Connect your Telegram or MAX account to work with your existing conversations. Bots use separate credentials and their own messaging access.</p></details><details><summary>Does it act automatically?</summary><p>Your agent uses the tools when instructed. Recurring reviews and monitoring need an agent schedule or service configuration. You can configure permissions and ask before changes.</p></details></div></section>`
const footer = () => `<footer class="wrap footer"><a class="brand" href="/">${logo}</a><p>Open-source tools for conversations, knowledge and useful actions.</p><div>${link("Documentation", docs)}${link("About WireCat", "https://wirecat.dev/en/about")}<a href="/">Compare six approaches</a></div></footer><div class="toast" role="status" aria-live="polite"></div>`

const sources = () => `<div class="source-stack"><div><span>Telegram · Atlas team</span><p>“We’re launching Friday. Final copy by Thursday.”</p><small>Anna · project discussion</small></div><div><span>Telegram · Tom</span><p>“First results attached. Two cases need staging access.”</p><small>Tom · project DM</small></div><div><span>MAX · Launch planning</span><p>“Can we confirm who signs off before release?”</p><small>Marco · launch discussion</small></div></div>`

const workflow = () => `<section class="workflow-board wrap" id="uses"><h2 class="sr-only">From messages to a follow-up</h2><div class="workflow-tabs" role="tablist" aria-label="Explore the connected workflow">${[["messages", "Gather messages"], ["email", "Check the email"], ["notes", "Update the note"], ["followup", "Prepare the follow-up"]].map(([id, label], i) => `<button id="stage-${id}" role="tab" aria-controls="workflow-${id}" aria-selected="${i === 0}" tabindex="${i === 0 ? 0 : -1}" data-stage="${id}">${label}</button>`).join("")}</div><div class="workflow-content"><div id="workflow-messages" role="tabpanel" aria-labelledby="stage-messages"><div><h3>The agreement starts in your chats</h3><p>Ask your agent to gather the project decisions from Telegram and MAX. Each source keeps its identity.</p><p class="workflow-tool">WireCat · tg + max</p></div>${sources()}</div><div id="workflow-email" role="tabpanel" aria-labelledby="stage-email" hidden><div><h3>The latest update arrived by email</h3><p>Your agent can use Himalaya to check the supplier’s update alongside the messaging context.</p><p class="workflow-tool">Email integration · Himalaya</p></div><div class="email-artifact"><span>From: Nora · supplier</span><h4>Atlas delivery update</h4><p>The sample shipment is now due Thursday morning. Please confirm the delivery address before Wednesday.</p><p>Thanks,<br>Nora</p></div></div><div id="workflow-notes" role="tabpanel" aria-labelledby="stage-notes" hidden><div><h3>Keep the shared picture in your notes</h3><p>Ask your agent to update the Obsidian project note with the confirmed decisions and links to the underlying material.</p><p class="workflow-tool">Knowledge workflow · Obsidian</p></div><div class="note-artifact"><span>Projects / Atlas.md</span><h4>Atlas · next steps</h4><ul><li>Launch: Friday</li><li>Samples: Thursday morning</li><li>Confirm address before Wednesday</li><li>Provide Tom with staging access</li></ul><p>Sources: project messages + supplier email</p></div></div><div id="workflow-followup" role="tabpanel" aria-labelledby="stage-followup" hidden><div><h3>A reply with the whole picture</h3><p>Your agent has the information to prepare a specific follow-up. Review the draft before choosing an action.</p><p class="workflow-tool">Reply through · tg or max</p></div><div class="note-artifact"><span>Draft to the Atlas team</span><blockquote>Samples are due Thursday morning. I’ll confirm the address with Nora before Wednesday and arrange Tom’s staging access. We’re still aiming for Friday’s launch.</blockquote><p class="draft-status">Ready for your review</p></div></div></div><p class="workflow-footnote">Email uses the third-party Himalaya CLI; Obsidian is your existing note vault. This workflow needs those tools configured alongside WireCat.</p></section>`

function content(v) {
  switch (v.id) {
    case "direct": return `<section class="hero wrap split-hero">${intro(v, link("See what it can do", "#uses"))}${demo(["reply", "find", "brief"], "reply", true)}</section>${outcomes()}${segments()}${trust()}${extension(true)}${setup()}${faq()}`
    case "memory": return `<section class="hero wrap memory-hero">${intro(v, link("Explore a remembered conversation", "#memory-demo"))}<div class="memory-strip"><p>Someone said it.<br><strong>Your agent can find it.</strong></p><div><span>A recommendation</span><span>A decision</span><span>A promise</span><span>A document</span></div></div></section><section class="section wrap memory-evidence" id="memory-demo"><div><h2>Remember the idea.<br>Recover the conversation.</h2><p>You don’t always remember the exact words. Conversation search can match meaning in the history you’ve built and indexed.</p><p class="micro">Set up conversation builds and embeddings for semantic retrieval. Your agent can inspect the original messages.</p></div>${demo(["find", "brief", "reply"], "find")}</section>${outcomes("A memory you can do something with")}${trust()}${segments()}${setup("Connect your agent to your conversation history")}`
    case "context": return `<section class="hero wrap context-hero">${intro(v, link("Follow the context", "#uses"))}<div class="context-mechanism"><h2 class="sr-only">How the context comes together</h2>${sources()}<div class="context-payoff"><h3>A clear brief.<br>A better follow-up.</h3><p>Decisions, changes and open questions, with the original messages a click away.</p>${link("See the brief", "#context-demo")}</div></div></section>${outcomes("The context to make your next move")}<section class="section wrap wide-demo" id="context-demo"><div class="section-intro"><h2>Start the call with the substance</h2><p>Move between the brief and the follow-up. The source material stays inspectable.</p></div>${demo(["brief", "reply", "find"], "brief")}</section>${segments()}${extension()}${trust()}${setup()}`
    case "audiences": return `<section class="hero wrap audience-hero">${intro(v)}</section>${segments(true)}<section class="section wrap audience-demo" id="audience-demo"><div class="section-intro"><h2>Different tasks. The same agent.</h2><p>Choose a use above or switch examples here.</p></div>${demo(["brief", "bot", "admin"], "brief")}</section>${trust()}<section class="section wrap admin-note"><h2>For the groups you run</h2><p>Have your agent review unanswered questions, prepare discussion summaries or preview moderation before applying your rules. Configure a schedule when you want recurring checks.</p>${link("Explore group administration", `${docs}/tg/groups`)}</section>${setup("Choose a messenger. Put your agent to work.")}${faq()}`
    case "workflow": return `<section class="hero wrap workflow-hero">${intro(v, link("Explore the workflow", "#uses"))}<div class="integration-line"><span>Telegram</span><span>MAX</span><span>Himalaya email</span><span>Obsidian notes</span></div></section>${workflow()}<section class="section wrap workflow-story"><div><h2>One request.<br>Several useful tools.</h2><p>Your agent can gather the conversation, check the latest email, maintain your project note and prepare the reply.</p></div><div><h3>Start with messaging</h3><p>WireCat’s tg and max connect your Telegram and MAX accounts. Use them on their own, or add your existing email and note tools.</p><h3>Keep the sources visible</h3><p>Ask for the messages, emails and notes behind a conclusion. Review the result before your agent changes anything.</p></div></section>${segments()}${trust()}${setup("Start by connecting Telegram or MAX")}`
    case "minimal": return `<section class="hero wrap minimal-hero">${intro(v)}<div class="agent-names"><span>Claude Code</span><span>Codex</span><span>Other CLI agents</span><span>MCP clients</span></div></section><section class="wrap minimal-demo" id="uses">${demo(["find", "brief", "reply"], "find")}</section><section class="section wrap minimal-proof"><h2>A few powerful things.<br>A simple way to ask.</h2><div><p><strong>Search and context.</strong> Find decisions, documents and conversations in your archive.</p><p><strong>Useful actions.</strong> Prepare replies, send files and work with your bots and groups.</p><p><strong>Your setup.</strong> Open source, local storage and configurable permissions.</p></div></section>${setup("Try one useful question")}`
  }
}

const document = (title, body, cls = "") => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${title} · WireCat homepage preview</title><link rel="icon" href="/icon.svg" type="image/svg+xml"><link rel="preload" href="/fonts/gNMKW3F-SZuj7xmf-HY.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/styles.css"><script src="/interactions.js" defer></script></head><body class="${cls}"><a class="skip-link" href="#main">Skip to content</a>${body}</body></html>`
await mkdir(root, { recursive: true })
for (const v of variants) await writeFile(new URL(`${v.id}.html`, root), document(v.name, `${header(v)}<main id="main">${content(v)}</main>${footer()}`, `variant-${v.id}`))
const gallery = `<header class="site-header wrap"><a class="brand" href="/">${logo}</a><span>Homepage exploration</span></header><main id="main" class="wrap gallery"><h1>Six ways to<br>introduce <em>WireCat.</em></h1><p class="lede">The same product, six different arguments. Compare the wording, the order and what each page puts in front of you first.</p><div class="gallery-list">${variants.map((v, i) => `<a href="/${v.id}" class="gallery-option"><span class="variant-index">${i + 1}</span><div><h2>${v.name}</h2><p>${v.description}</p><span>${v.angle}</span></div>${arrow}</a>`).join("")}</div><p class="gallery-note">Every page includes working example tabs, inspectable sources, a theme switch and Telegram/MAX installation choices. These are local design previews; setup links lead to the public documentation.</p></main>${footer()}`
await writeFile(new URL("index.html", root), document("Six approaches", gallery, "gallery-page"))
console.log("Built six homepage variants and the comparison index.")
