const root=document.documentElement
const themeButtons=Array.from(document.querySelectorAll('.theme-switch,.theme-toggle'))
function setTheme(dark){root.classList.toggle('dark',dark);root.classList.toggle('light',!dark);themeButtons.forEach(b=>b.setAttribute('aria-label',`Switch to ${dark?'light':'dark'} theme`))}
try{setTheme(localStorage.getItem('wirecat-memory-theme')==='dark')}catch{}
themeButtons.forEach(button=>button.addEventListener('click',()=>{const dark=!root.classList.contains('dark');setTheme(dark);try{localStorage.setItem('wirecat-memory-theme',dark?'dark':'light')}catch{}}))
const palette=document.querySelector('#palette');if(palette){palette.value=root.dataset.palette;palette.addEventListener('change',()=>{root.dataset.palette=palette.value})}
let toastTimer
function notify(message){const t=document.querySelector('.toast');t.textContent=message;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),2300)}
for(const button of document.querySelectorAll('[data-prompt]'))button.dataset.copy=button.dataset.prompt
for(const button of document.querySelectorAll('.footer-host [data-copy]')){const tool=button.dataset.copy.includes('/max-cli')?'max':'tg';const cmd=navigator.userAgent.includes('Windows')?`& ([scriptblock]::Create((Invoke-RestMethod 'https://wirecat.dev/install.ps1'))) -Tool ${tool} -Agent all`:`npm install -g @leemour/${tool}-cli && ${tool} skill install --for all`;button.dataset.copy=cmd;const code=button.closest('.cmd')?.querySelector('code');if(code)code.textContent=cmd}
document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(button.dataset.copy);notify(button.closest('.command,.footer-install')?'Command copied.':'Request copied. Paste it into your agent.')}catch{notify('Clipboard unavailable. Select the text and copy it manually.')}}))
const menus=Array.from(document.querySelectorAll('[data-connect]'))
menus.forEach(menu=>{menu.addEventListener('toggle',()=>{if(menu.open)menus.filter(m=>m!==menu).forEach(m=>{m.open=false})});menu.querySelectorAll('[data-connect-provider]').forEach(button=>button.addEventListener('click',()=>{const tool=button.dataset.connectProvider;menu.querySelectorAll('[data-connect-provider]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const prompt=window.wirecatSetupPrompts[tool];menu.querySelector('.agent-prompt').textContent=prompt;menu.querySelector('.copy-agent').dataset.copy=prompt;const command=`npm install -g @leemour/${tool}-cli && ${tool} skill install --for all`;menu.querySelector('.command code').textContent=command;menu.querySelector('.command [data-copy]').dataset.copy=command;menu.querySelector('.connect-guide').href=`https://wirecat.dev/en/docs/installation#${tool}`}))})
document.addEventListener('click',event=>menus.forEach(menu=>{if(menu.open&&!menu.contains(event.target))menu.open=false}))
document.addEventListener('keydown',event=>{if(event.key==='Escape'){const menu=menus.find(m=>m.open);if(menu){menu.open=false;menu.querySelector('summary').focus();event.preventDefault()}}})
function tabs(buttonSelector,panelSelector,key){const buttons=Array.from(document.querySelectorAll(buttonSelector));const panels=Array.from(document.querySelectorAll(panelSelector));const select=(button,focus=false)=>{buttons.forEach(b=>{const active=b===button;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});panels.forEach(p=>{p.hidden=p.id!==button.getAttribute('aria-controls')});if(focus)button.focus()};buttons.forEach((button,index)=>{button.addEventListener('click',()=>select(button));button.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(index+1)%buttons.length;if(event.key==='ArrowLeft')next=(index+buttons.length-1)%buttons.length;if(event.key==='Home')next=0;if(event.key==='End')next=buttons.length-1;if(next!==undefined){event.preventDefault();select(buttons[next],true)}})});if(key){const requested=new URL(location.href).searchParams.get('case');const selected=buttons.find(b=>b.dataset.walkthrough===requested);if(selected)select(selected)}}
tabs('[data-hero-case]','.memory-panel');tabs('[data-walkthrough]','.walkthrough-panel',true)
function calculate(){const read=(selector)=>Math.max(0,Number(document.querySelector(selector).value)||0);const m=read('[data-calc="messages"]'),c=read('[data-calc="chats"]'),r=read('[data-calc="replies"]');document.querySelectorAll('[data-calc]').forEach(input=>{document.querySelector(`[data-volume="${input.dataset.calc}"]`).textContent=input.value});const t=Object.fromEntries(Array.from(document.querySelectorAll('[data-timing]')).map(input=>[input.dataset.timing,Math.max(0,Number(input.value)||0)]));const manual=(m*t.readSeconds+c*t.contextSeconds)/60+r*t.writeMinutes;const assisted=t.summaryMinutes+c*t.checkContextSeconds/60+r*t.checkReplyMinutes;const saved=manual-assisted;document.querySelector('#saved-minutes').textContent=Math.abs(saved).toFixed(0);document.querySelector('#saved-monthly').textContent=(Math.abs(saved)*22/60).toFixed(1);document.querySelector('#manual-time').textContent=manual.toFixed(0);document.querySelector('#agent-time').textContent=assisted.toFixed(0);document.querySelector('#saving-label').textContent=saved>=0?'Time you could free up':'Manual work is faster with these assumptions'}
if(document.querySelector('[data-calc]')){document.querySelectorAll('[data-calc],[data-timing]').forEach(input=>input.addEventListener('input',calculate));calculate()}
