export const copy = {
  en: {
    all: "All",
    backToMessages: "Back to messages",
    suggestionsTitle: "Suggestions",
    clear: "Clear query",
    clearDate: "Clear date filter",
    previous: "Showing the previous valid results.",
    syntaxHelp:
      "Use AND, OR and NOT, group with parentheses, or choose field values below. Dates use UTC. Clear the query to see the whole sample archive.",
    filters: { text: "Text", chat: "Chat", from: "Person" },
    suggestions: {
      sampleDay: "Today",
      sampleMonth: "This month",
      fromSampleDay: "From two days ago onward",
      beforeNextDay: "Before tomorrow",
      sampleWeek: "Five-day sample window",
    },
    eyebrow: "A search worth following",
    title: "Flexible search conditions",
    intro: "Find a message across your chats. See what came before, what changed, and where the answer comes from.",
    archive: "Sample archive · 50 messages · 6 chats",
    label: "Search your conversations",
    placeholder: "A word, a person, a date…",
    invalid: "Complete the query or choose a suggestion.",
    unsupported: "This field or operator is not supported. Open Syntax & fields above.",
    sampleError: "Not available in this sample archive. Choose a suggestion or open the search guide.",
    hint: "Choose a field for sample values. Use All to explore the archive.",
    chat: "Chat",
    person: "Person",
    date: "Date",
    attachment: "Files",
    copy: "Copy command",
    copied: "Copied",
    matches: "Matches",
    context: "Context",
    summary: "Summary",
    results: "matches",
    empty: "No matches in this sample archive.",
    emptyHelp: "Try another word or remove a filter. Search never expands your query automatically.",
    contextHint: "Select a message to see the conversation around it.",
    quote: "Selected message",
    source: "View source",
    summaryTitle: "What the retrieved messages establish",
    summaryHint:
      "These facts appear only when their supporting messages are retrieved. No live AI or personal account is connected.",
    deadline: "The final invoice deadline is {date}.",
    budget: "Extra work is awaiting approval and a final quote.",
    noFacts: "No prepared fact is supported by this result set. Open a message to read its context.",
    scope: "A live demo over fictional messages. Your CLI searches only the archive already stored on your machine.",
    reference: "Search guide",
    advanced: "Syntax & fields",
    unavailable:
      "This is a preview of the new search profile. The guide is available on GitHub; CLI releases follow separately.",
    countLabel: "Search results",
    keyboard: "↑ ↓ to browse · Enter to insert · Esc to close",
    copyFailed: "Select the command below to copy it.",
    utc: "Dates use UTC",
  },
  ru: {
    all: "Все",
    backToMessages: "К сообщениям",
    suggestionsTitle: "Подсказки",
    clear: "Очистить запрос",
    clearDate: "Убрать фильтр даты",
    previous: "Показаны результаты предыдущего корректного запроса.",
    syntaxHelp:
      "Используйте AND, OR и NOT, скобки или выберите значения полей ниже. Даты в UTC. Очистите запрос, чтобы увидеть весь пример архива.",
    filters: { text: "Текст", chat: "Чат", from: "Человек" },
    suggestions: {
      sampleDay: "Сегодня",
      sampleMonth: "Этот месяц",
      fromSampleDay: "Начиная с позавчера",
      beforeNextDay: "До завтра",
      sampleWeek: "Пять дней примера",
    },
    eyebrow: "Поиск, который ведёт к ответу",
    title: "Гибкие условия поиска",
    intro: "Найдите сообщение в своих чатах. Узнайте, что было до него, что изменилось и на чём основан ответ.",
    archive: "Пример архива · 50 сообщений · 6 чатов",
    label: "Поиск по переписке",
    placeholder: "Слово, человек, дата…",
    invalid: "Допишите запрос или выберите подсказку.",
    unsupported: "Это поле или оператор не поддержаны. Откройте «Синтаксис и поля» выше.",
    sampleError: "Недоступно в этом примере архива. Выберите подсказку или откройте руководство по поиску.",
    hint: "Выберите поле, чтобы увидеть значения. Вкладка «Все» покажет весь архив.",
    chat: "Чат",
    person: "Человек",
    date: "Дата",
    attachment: "Файлы",
    copy: "Копировать команду",
    copied: "Скопировано",
    matches: "Совпадения",
    context: "Контекст",
    summary: "Вывод",
    results: "совпадений",
    empty: "В примере архива совпадений нет.",
    emptyHelp: "Попробуйте другое слово или уберите фильтр. Поиск не расширяет запрос автоматически.",
    contextHint: "Выберите сообщение, чтобы увидеть разговор вокруг него.",
    quote: "Выбранное сообщение",
    source: "Открыть источник",
    summaryTitle: "Что подтверждают найденные сообщения",
    summaryHint:
      "Факты появляются только вместе с подтверждающими сообщениями. Живой агент и личный аккаунт не подключены.",
    deadline: "Окончательный срок счёта — {date}.",
    budget: "Дополнительная работа ждёт согласования и окончательной сметы.",
    noFacts: "Для этой выдачи нет подтверждённого готового вывода. Откройте сообщение и прочитайте контекст.",
    scope: "Живой пример на вымышленных сообщениях. CLI ищет только в архиве, уже сохранённом на вашем компьютере.",
    reference: "Справка поиска",
    advanced: "Синтаксис и поля",
    unavailable: "Это предпросмотр нового профиля поиска. Справка доступна на GitHub; выпуск CLI — отдельный шаг.",
    countLabel: "Результаты поиска",
    keyboard: "↑ ↓ выбор · Enter вставка · Esc закрытие",
    copyFailed: "Выделите команду ниже, чтобы скопировать её.",
    utc: "Даты в UTC",
  },
  es: {
    all: "Todos",
    backToMessages: "Volver a los mensajes",
    suggestionsTitle: "Sugerencias",
    clear: "Borrar consulta",
    clearDate: "Quitar filtro de fecha",
    previous: "Se muestran los últimos resultados válidos.",
    syntaxHelp:
      "Usa AND, OR y NOT, paréntesis o los campos de abajo. Las fechas usan UTC. Borra la consulta para ver todo el archivo de ejemplo.",
    filters: { text: "Texto", chat: "Chat", from: "Persona" },
    suggestions: {
      sampleDay: "Hoy",
      sampleMonth: "Este mes",
      fromSampleDay: "Desde anteayer",
      beforeNextDay: "Antes de mañana",
      sampleWeek: "Cinco días de ejemplo",
    },
    eyebrow: "Una búsqueda que lleva a la respuesta",
    title: "Condiciones de búsqueda flexibles",
    intro: "Encuentra un mensaje entre tus chats. Lee lo que pasó antes, qué cambió y de dónde sale la respuesta.",
    archive: "Archivo de ejemplo · 50 mensajes · 6 chats",
    label: "Busca en tus conversaciones",
    placeholder: "Una palabra, una persona, una fecha…",
    invalid: "Completa la consulta o elige una sugerencia.",
    unsupported: "Este campo u operador no está disponible. Abre Sintaxis y campos arriba.",
    sampleError: "No está disponible en este archivo de ejemplo. Elige una sugerencia o abre la guía de búsqueda.",
    hint: "Elige un campo para ver valores. Usa Todos para explorar el archivo.",
    chat: "Chat",
    person: "Persona",
    date: "Fecha",
    attachment: "Archivos",
    copy: "Copiar comando",
    copied: "Copiado",
    matches: "Coincidencias",
    context: "Contexto",
    summary: "Resumen",
    results: "coincidencias",
    empty: "No hay coincidencias en este archivo de ejemplo.",
    emptyHelp: "Prueba otra palabra o elimina un filtro. La búsqueda nunca amplía tu consulta automáticamente.",
    contextHint: "Selecciona un mensaje para ver la conversación que lo rodea.",
    quote: "Mensaje seleccionado",
    source: "Ver fuente",
    summaryTitle: "Lo que confirman los mensajes recuperados",
    summaryHint:
      "Estos hechos aparecen solo cuando se recuperan sus mensajes de respaldo. No hay IA en vivo ni una cuenta personal conectada.",
    deadline: "La fecha definitiva de la factura es el {date}.",
    budget: "El trabajo adicional está pendiente de aprobación y del presupuesto definitivo.",
    noFacts: "Ningún hecho preparado está respaldado por estos resultados. Abre un mensaje para leer el contexto.",
    scope: "Demo interactiva con mensajes ficticios. Tu CLI busca solo en el archivo guardado en tu equipo.",
    reference: "Guía de búsqueda",
    advanced: "Sintaxis y campos",
    unavailable:
      "Vista previa del nuevo perfil de búsqueda. La guía está en GitHub; la publicación del CLI es un paso aparte.",
    countLabel: "Resultados de búsqueda",
    keyboard: "↑ ↓ explorar · Enter insertar · Esc cerrar",
    copyFailed: "Selecciona el comando de abajo para copiarlo.",
    utc: "Fechas en UTC",
  },
} as const
