// pnpm docs:data-model <schema.md> [--source] — rewrites the table reference in content/docs/data-model*.mdx
// from cli-messaging's docs/storage/schema.md. English comes from the schema doc, with content/data/data-model/en.json
// filling what it leaves empty; ru and es come from their JSON files, keyed the same way. --source writes
// content/data/data-model/source.json: every key with its English text, the list a translation must cover.
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

type Column = { name: string; type: string; flags: string; ref: string; meaning: string }
type Table = { name: string; desc: string; cols: Column[]; fts: string[] | null }
type Area = { name: string; desc: string; tables: Table[] }

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const dataDir = join(root, "content/data/data-model")
const pages = { en: "data-model.mdx", ru: "data-model.ru.mdx", es: "data-model.es.mdx" } as const
type Lang = keyof typeof pages
const START = "{/* tables:start — generated by pnpm docs:data-model */}"
const END = "{/* tables:end */}"

export function parseSchema(markdown: string): Area[] {
  const areas: Area[] = []
  let area: Area | undefined
  let table: (Table & { described?: boolean }) | undefined
  let para: string[] = []
  const takePara = () => {
    const text = para.join(" ").trim()
    para = []
    return text
  }
  const describe = () => {
    if (table && !table.described) {
      table.desc = takePara()
      table.described = true
    }
  }
  for (const line of [...markdown.split("\n"), "## END"]) {
    if (line.startsWith("## ")) {
      describe()
      const name = line.slice(3).trim()
      area = ["Conventions", "Dropped or merged", "END"].includes(name) ? undefined : { name, desc: "", tables: [] }
      if (area) areas.push(area)
      table = undefined
      para = []
      continue
    }
    if (!area) continue
    if (line.startsWith("### ")) {
      if (table) describe()
      else area.desc = takePara()
      table = { name: /`([^`]+)`/.exec(line)?.[1] ?? "", desc: "", cols: [], fts: null }
      area.tables.push(table)
      para = []
      continue
    }
    if (line.startsWith("*Change:*") || line.startsWith("*Keys")) {
      describe()
      continue
    }
    if (line.startsWith("| `") && table) {
      describe()
      const cells = line
        .trim()
        .replace(/^\|/, "")
        .replace(/\|$/, "")
        .split(" | ")
        .map((cell) => cell.trim())
      const name = /`([^`]+)`/.exec(cells[0] ?? "")?.[1] ?? ""
      table.cols.push({
        name,
        type: cells[1] ?? "",
        flags: cells[2] ?? "",
        ref: cells[3] ?? "",
        meaning: cells[4] ?? "",
      })
      continue
    }
    if (line.startsWith("|") || line.startsWith("```")) continue
    if (line.startsWith("CREATE VIRTUAL TABLE") && table && table.fts === null) {
      const args = line.slice(line.indexOf("(") + 1, line.lastIndexOf(")"))
      table.fts = args
        .split(",")
        .map((arg) => arg.trim())
        .filter((arg) => arg && !arg.includes("="))
      continue
    }
    if (line.trim()) para.push(line.trim())
  }
  return areas
}

/** Every text the page shows, keyed so a translation can say which one it translates. */
export function englishTexts(areas: Area[], fills: Record<string, string>): Record<string, string> {
  const texts: Record<string, string> = {}
  for (const [key, value] of Object.entries(fills)) if (key.startsWith("ui:")) texts[key] = value
  for (const area of areas) {
    texts[`area-name:${area.name}`] = area.name
    texts[`area:${area.name}`] = fills[`area:${area.name}`] ?? area.desc
    for (const table of area.tables) {
      if (table.fts) continue
      const desc = fills[`table:${table.name}`] ?? table.desc
      if (desc) texts[`table:${table.name}`] = desc
      for (const col of table.cols) {
        const key = `col:${table.name}.${col.name}`
        const meaning = fills[key] ?? col.meaning
        if (meaning) texts[key] = meaning
      }
    }
  }
  return texts
}

const inlineCode = (text: string) => [...text.matchAll(/`[^`]+`/g)].map((match) => match[0]).sort()

export function translationGaps(english: Record<string, string>, translated: Record<string, string>): string[] {
  const gaps: string[] = []
  for (const key of Object.keys(english)) {
    if (!(key in translated)) gaps.push(`missing ${key}`)
    else if (JSON.stringify(inlineCode(english[key] ?? "")) !== JSON.stringify(inlineCode(translated[key] ?? "")))
      gaps.push(`inline code differs in ${key}`)
  }
  for (const key of Object.keys(translated)) if (!(key in english)) gaps.push(`orphan ${key}`)
  return gaps
}

const cell = (text: string) => text.replace(/\|/g, "\\|").replace(/\{/g, "\\{").replace(/</g, "&lt;")

export function renderTables(areas: Area[], texts: Record<string, string>): string {
  const t = (key: string) => texts[key] ?? ""
  const out: string[] = []
  for (const area of areas) {
    out.push(`### ${t(`area-name:${area.name}`)}`, "")
    if (t(`area:${area.name}`)) out.push(t(`area:${area.name}`), "")
    for (const table of area.tables) {
      out.push(`#### \`${table.name}\``, "")
      if (table.fts) {
        out.push(`${t("ui:fts")} ${table.fts.map((column) => `\`${column}\``).join(", ")}.`, "")
        continue
      }
      if (t(`table:${table.name}`)) out.push(t(`table:${table.name}`), "")
      out.push(`| ${t("ui:column")} | ${t("ui:type")} | ${t("ui:meaning")} |`, "| --- | --- | --- |")
      for (const col of table.cols) {
        const type = [col.type, col.flags].filter(Boolean).join(", ") + (col.ref ? ` ${col.ref}` : "")
        const fallback = col.name === "id" ? t(col.flags.includes("PK") ? "ui:pk" : "ui:pending") : ""
        const meaning = t(`col:${table.name}.${col.name}`) || fallback
        out.push(`| \`${col.name}\` | ${cell(type)} | ${cell(meaning)} |`)
      }
      out.push("")
    }
  }
  return out.join("\n").trimEnd()
}

const readJson = (file: string) => JSON.parse(readFileSync(join(dataDir, file), "utf8")) as Record<string, string>

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const [schemaPath, flag] = process.argv.slice(2)
  if (!schemaPath) {
    console.error("usage: pnpm docs:data-model <path to cli-messaging docs/storage/schema.md> [--source]")
    process.exit(2)
  }
  const areas = parseSchema(readFileSync(schemaPath, "utf8"))
  const english = englishTexts(areas, readJson("en.json"))
  if (flag === "--source") {
    writeFileSync(join(dataDir, "source.json"), `${JSON.stringify(english, null, 2)}\n`)
    console.log(`${Object.keys(english).length} texts → content/data/data-model/source.json`)
    process.exit(0)
  }
  let failed = false
  for (const [lang, page] of Object.entries(pages) as [Lang, string][]) {
    const texts = lang === "en" ? english : readJson(`${lang}.json`)
    const gaps = lang === "en" ? [] : translationGaps(english, texts)
    if (gaps.length) {
      console.error(`${lang}: ${gaps.length} problems\n  ${gaps.slice(0, 20).join("\n  ")}`)
      failed = true
      continue
    }
    const path = join(root, "content/docs", page)
    const text = readFileSync(path, "utf8")
    const start = text.indexOf(START)
    const end = text.indexOf(END)
    if (start < 0 || end < start) throw new Error(`${page}: table markers missing`)
    writeFileSync(path, `${text.slice(0, start + START.length)}\n\n${renderTables(areas, texts)}\n\n${text.slice(end)}`)
  }
  if (failed) process.exit(1)
  console.log("data model tables written")
}
