import { mkdir, readFile, writeFile } from "node:fs/promises"
import { wirecatLogoSvg } from "../../lib/brand.ts"
import { wordsFor } from "../../lib/words.ts"

const root = new URL("./", import.meta.url)
const landing = JSON.parse(await readFile(new URL("../../lib/landing/en.json", import.meta.url), "utf8"))
const site = JSON.parse(await readFile(new URL("../../site.config.json", import.meta.url), "utf8"))
const docs = "https://wirecat.dev/en/docs"
const esc = (s) => String(s).replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c])
const plain = (s) => s.replace(/<svg[\s\S]*?<\/svg>/g, "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim()
const svg = (path) => `<svg viewBox="0 0 24 24" aria-hidden="true">${path}</svg>`
const icon = {
  arrow: svg('<path d="M5 12h14m-6-6 6 6-6 6"/>'),
  copy: svg('<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V4H4v12h4"/>'),
  moon: svg('<path d="M20 15.5A8.5 8.5 0 0 1 8.5 4a8.5 8.5 0 1 0 11.5 11.5Z"/>'),
  down: svg('<path d="m6 9 6 6 6-6"/>'),
  search: svg('<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>'),
  account: svg('<circle cx="12" cy="8" r="4"/><path d="M5 21v-3c0-4 14-4 14 0v3"/>'),
  bot: svg('<rect x="4" y="7" width="16" height="13" rx="3"/><path d="M12 3v4M8 12h1m6 0h1M9 16h6"/>'),
  group: svg('<circle cx="8" cy="8" r="3"/><circle cx="17" cy="9" r="3"/><path d="M2 20v-2c0-5 12-5 12 0v2m1-5c4-2 7 0 7 3v2"/>'),
  note: svg('<path d="M6 3h9l4 4v14H6Z"/><path d="M14 3v5h5M9 12h7M9 16h5"/>'),
  verify: svg('<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>'),
  reply: svg('<path d="m9 5-6 6 6 6M3 11h10c5 0 8 3 8 8"/>'),
  telegram: svg('<path d="m3 11 18-7-5 17-5-6-4 3 1-6 10-6-8 8Z"/>'),
  max: svg('<path d="M5 6h14v11h-8l-5 4V6Z"/><path d="m9 13 2-3 2 3 2-3"/>'),
  email: svg('<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>'),
  clock: svg('<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>'),
}
const link = (text, href, cls = "text-link") => `<a class="${cls}" href="${href}">${text}${icon.arrow}</a>`
const config = [
 {id:"chat",name:"Original conversation",palette:"classic",type:"outcomes",hero:["context","search","commitments"],tools:"strip",mode:"chat",desc:"Original request, tool calls and response. Continue the original conversation inside the hero."},
 {id:"walkthrough",name:"Conversation in steps",palette:"classic",type:"outcomes",hero:["context","search","commitments"],tools:"strip",mode:"walkthrough",desc:"The same original exchanges, one at a time. Continue the example to see how the agent gathers more context."},
 {id:"answer",name:"Finished result first",palette:"classic",type:"outcomes",hero:["context","search","commitments"],tools:"strip",mode:"answer",desc:"The original final request and result, with earlier requests and tool calls available above it."},
]
const captions = {
  context: { title: "Prepare for a call", question: "Gather the decisions, risks and open questions for tomorrow’s Atlas call.", answerTitle: "The call can start with the remaining decisions", answer: '<ul><li><b>Payment tests:</b> Tom has results; the production check still needs access.</li><li><b>Final copy:</b> Anna needs it before launch.</li><li><b>Decide on the call:</b> owners, deadlines and whether the remaining risk changes the launch.</li></ul><p class="result-note">A 20-minute agenda, based on the project group, design group and DMs.</p>', pick: ["Test payments work.", "launching", "final copy"], caption: "An agenda assembled from the relevant chats" },
  search: { title: "Find recommendations", question: "Find SQL course recommendations across Telegram and MAX. I want exercises and feedback.", answerTitle: "The workshop is the better lead", answer: '<p>A participant confirms weekly exercises and feedback on mistakes. The video course helped with basics, but feedback isn’t confirmed.</p><ul><li><b>Start with:</b> the workshop.</li><li><b>Check next:</b> course level, assignment reviews and current availability.</li></ul>', pick: ["weekly exercises", "nobody reviewed"], caption: "A comparison that uses the surrounding messages" },
  commitments: { title: "Follow up with context", question: "Check who needs my reply and whether Tom already sent the design. Draft the right follow-up.", answerTitle: "Tom already sent the first draft", answer: '<p>A reminder saying he hasn’t sent anything would miss the history.</p><blockquote>Tom, thanks for the first draft! When can you send the final version with our feedback incorporated?</blockquote><p class="result-note">The reply is a draft. The budget decision stays with you.</p>', pick: ["first design draft", "design on Wednesday"], caption: "A reply that reflects what has already happened" },
  inbox: { title: "Get a morning briefing", question: "Who is waiting for my reply, and what should I handle first?", answerTitle: "Your first 15 minutes", answer: '<ol><li><b>Marco’s budget request:</b> the contractor is waiting on your decision.</li><li><b>Anna’s meeting:</b> confirm the new time, 19:30.</li><li><b>Mum’s voice note:</b> confirm whether you can drive her tomorrow.</li></ol><p class="result-note">News is kept in a separate list for later.</p>', pick: ["budget", "19:30", "appointment"], caption: "Priorities from messages and a transcribed voice note" },
  moderation: { title: "Review a group", question: "Show violations of the Community group’s rules and a proposed action plan. Don’t delete anything yet.", answerTitle: "A moderation plan for your review", answer: '<p>Two promotional messages violate the saved link rule.</p><ul><li>Proposed action: delete those two messages.</li><li>Keep the recording question.</li><li>Remove no members.</li></ul><p class="result-note">This is a preview. No action has been taken.</p>', pick: ["websites", "packages", "recording"], caption: "The proposed actions are visible before you approve them" },
  bot: { title: "Answer a customer", question: "Check Anna’s order questions received by the sales bot and draft a reply.", answerTitle: "Confirm what is known; check the requested change", answer: '<blockquote>Delivery is agreed for Friday and your address is confirmed. I’ll check with the team whether we can move it to tomorrow and get back to you.</blockquote><p class="result-note">The date change wasn’t confirmed in the bot’s messages. The draft makes no new promise.</p>', pick: ["Delivery agreed", "move it to tomorrow"], caption: "A support reply based on the messages this bot received" },
  files: { title: "Collect the latest files", question: "Find the current Atlas contract, invoices and presentation. Check project groups and DMs.", answerTitle: "The current files, without losing old versions", answer: '<ul><li><b>Contract:</b> contract-final.pdf from Anna’s DMs.</li><li><b>Invoice:</b> invoice-phase-1.pdf from the project group.</li><li><b>Presentation:</b> presentation-v3.pdf from the design group.</li></ul><p class="result-note">Older versions remain in chat history. Nothing is sent to the customer.</p>', pick: ["Invoice for", "presentation v3"], caption: "One current document set from several conversations" },
  schedule: { title: "Schedule messages", question: "Remind me to check the invoice in two hours. Ask Anna and Tom for updates in one hour, privately.", answerTitle: "Reminders and follow-ups scheduled", answer: '<ul><li><b>Saved Messages:</b> check the invoice in two hours.</li><li><b>Anna:</b> ask for final copy in one hour.</li><li><b>Tom:</b> ask for payment status in one hour.</li></ul><p class="result-note">Telegram delivers scheduled messages even when your laptop is off.</p>', pick: [], caption: "A message that arrives at the right time" },
}
function evidence(session) {
  const found = []
  for (const step of session.steps) for (const match of step.html.matchAll(/<details class="evidence-message"[\s\S]*?<blockquote>([\s\S]*?)<\/blockquote><\/details>/g)) {
    const meta = plain(match[0].match(/class="evidence-meta">([\s\S]*?)<\/span>/)?.[1] ?? "Source message").replace(/ · Oct \d+, \d{4}/, "")
    const author=plain((match[0].match(/<strong>([\s\S]*?)<\/strong>/)?.[1] ?? "").replace(/<span class="evidence-id">[\s\S]*?<\/span>/,""));
    const label=author && !meta.startsWith(author+" ·") ? `${author} · ${meta}` : meta;
    const quote = plain(match[1]);if (!found.some(x => x.quote === quote && x.meta === label)) found.push({meta:label,quote})
  }
  return found
}
function caseData(id) {
  const session = landing.sessions.find(s => s.id === id)
  const c = captions[id];const all = evidence(session)
  const chosen = c.pick.map(term => all.find(s => s.quote.toLowerCase().includes(term.toLowerCase()))).filter(Boolean).filter((s,i,a)=>a.findIndex(x=>x.quote===s.quote&&x.meta===s.meta)===i).slice(0,3)
  return {...c, id, session, sources:chosen, prompt: `Use my WireCat messaging tools. ${c.question}`}
}
const cases = Object.fromEntries(Object.keys(captions).map(id => [id,caseData(id)]))

function connect(scope, label = "Connect your agent", small = false) {
  return `<details class="connect-dropdown" data-connect><summary class="button ${small ? "small" : ""}">${label}${icon.down}</summary><div class="connect-panel"><p class="connect-intro">Copy a setup request into your AI agent.</p><div class="connect-provider" role="group" aria-label="Choose messenger for setup"><button type="button" data-connect-provider="tg" aria-pressed="true">Telegram</button><button type="button" data-connect-provider="max" aria-pressed="false">MAX</button></div><p class="prompt-label">Ask your agent to install and connect</p><pre class="agent-prompt">${esc(wordsFor("en").onboarding.prompt("tg","@leemour/tg-cli"))}</pre><button class="button copy-agent" type="button" data-copy="${esc(wordsFor("en").onboarding.prompt("tg","@leemour/tg-cli"))}">Copy request for your agent${icon.copy}</button><details class="manual-install"><summary>Or copy the terminal command</summary><div class="command"><code>npm install -g @leemour/tg-cli && tg skill install --for all</code><button type="button" data-copy="npm install -g @leemour/tg-cli && tg skill install --for all" aria-label="Copy terminal installation command">${icon.copy}</button></div></details><a class="text-link connect-guide" href="${docs}/installation#tg">Setup and sign-in guide${icon.arrow}</a><p class="connect-small">The request runs in your agent. Signing in adds a device to your account.</p></div></details>`
}
const header = (v) => `<nav class="comparison-bar" aria-label="Homepage variants"><a href="/">Hero variants</a><div>${config.map(c=>`<a href="/${c.id}" ${c.id===v?.id?'aria-current="page"':''}>${c.name}</a>`).join("")}</div><a href="http://127.0.0.1:4327/">Previous Memory variants</a></nav><header class="wrap site-header"><a class="brand" href="/" aria-label="WireCat previews">${wirecatLogoSvg}</a><nav aria-label="Site navigation"><a href="${docs}/tg">Telegram</a><a href="${docs}/max">MAX</a><a href="https://wirecat.dev/en/about">About</a><button type="button" class="theme-switch" aria-label="Switch to dark theme">${icon.moon}</button>${connect("header","Connect your agent",true)}</nav></header>`
const colorControls = () => ""
function hero(v) {
  const tools = `<div class="connector-list" aria-label="Messenger and email tools"><span>${icon.telegram}Telegram</span><span>${icon.max}MAX</span><span>${icon.email}Email</span></div>`
  return `<section class="hero wrap memory-hero"><div class="hero-copy"><h1>Memory for your messages.<br><em>Context for your agent.</em></h1><p class="lede">Find what was said, catch up on what matters and reply with the full context. WireCat connects the AI agent you already use to your conversations and notes.</p><div class="hero-actions">${connect("hero")}</div>${tools}<p class="micro">Free, open-source tools that run on your computer.</p></div>${heroDemo(v)}</section>`
}
const terminalIcon=svg('<rect x="3" y="5" width="18" height="14" rx="3"/><path d="m7 9 3 3-3 3m6 0h4"/>')
function originalMarkup(step, prefix) {
 let html=step.html.replace(/class="([^"]+)"/g,(_,cls)=>`class="${cls.split(" ").map(token=>token==="step"?"walkthrough-step":token).join(" ")}"`).replace(/id="([^"]+)"/g,`id="${prefix}-$1"`)
 if(step.html.includes('class="ask step"'))html=html.replace('<p>',`<div class="message-role request-role">${icon.account}<span>Your request</span></div><p>`)
 else if(!step.tool)html=html.replace(/(<div class="say[^"]*">)/,`$1<div class="message-role response-role">${icon.bot}<span>Agent response</span></div>`)
 if(step.tool)html=html.replace('<pre>', '<span class="tool-output-label">Tool output · JSON</span><pre>')
 return html
}
function renderExchange(part,prefix){
 let html=""
 for(let i=0;i<part.length;i++){
  if(!part[i].tool){html+=originalMarkup(part[i],`${prefix}-${i}`);continue}
  const calls=[];while(i<part.length && part[i].tool){calls.push(originalMarkup(part[i],`${prefix}-${i}`));i++}i--
  html+=`<section class="tool-call-group" aria-label="Tool calls"><div class="message-role tool-role">${terminalIcon}<span>Tool calls</span><small>${calls.length} ${calls.length===1?"command":"commands"}</small></div>${calls.join("")}</section>`
 }
 return html
}
function exchanges(session) {
 const parts=[]
 for(const step of session.steps){if(step.html.includes('class="ask step"'))parts.push([]);parts.at(-1).push(step)}
 return parts
}
function originalDialogue(v,id,provider) {
 const session=(provider==="tg"?landing.sessions:landing.maxSessions).find(s=>s.id===id)
 const parts=exchanges(session);const prefix=`${v.id}-${id}-${provider}`
 const render=(part,index)=>renderExchange(part,`${prefix}-${index}`)
 if(v.mode==="chat")return `<div class="walkthrough hero-transcript">${render(parts[0],0)}<details class="continue-dialogue"><summary>Continue the original conversation</summary>${parts.slice(1).map((part,i)=>render(part,i+1)).join("")}</details></div>`
 if(v.mode==="walkthrough")return `<div class="exchange-demo" data-exchange-demo><div class="walkthrough hero-transcript">${parts.map((part,i)=>`<div class="exchange-frame" data-exchange-frame="${i}" ${i?"hidden":""}>${render(part,i)}</div>`).join("")}</div><div class="exchange-controls"><button type="button" data-previous-exchange disabled>Previous</button><span data-exchange-counter>Exchange 1 of ${parts.length}</span><button type="button" data-next-exchange>Continue example${icon.arrow}</button></div></div>`
 return `<div class="walkthrough hero-transcript result-first"><details class="previous-dialogue"><summary>Earlier requests and tool calls</summary>${parts.slice(0,-1).map((part,i)=>render(part,i)).join("")}</details>${render(parts.at(-1),parts.length-1)}</div>`
}
function heroDemo(v) {
 return `<section class="memory-demo original-demo" aria-label="Original landing examples"><h2 class="sr-only">Conversation with your AI agent</h2><div class="memory-demo-top"><span>Conversation with your AI agent</span><div class="demo-providers" role="group" aria-label="Messenger in this example"><button type="button" data-demo-provider="tg" aria-pressed="true">Telegram</button><button type="button" data-demo-provider="max" aria-pressed="false">MAX</button></div></div><div class="conversation-key" aria-label="Conversation roles"><span>${icon.account}Your request</span><span>${terminalIcon}Tool calls</span><span>${icon.bot}Agent response</span></div><div class="memory-tabs" role="tablist" aria-label="Choose a task">${v.hero.map((id,i)=>`<button type="button" role="tab" id="${v.id}-tab-${id}" aria-controls="${v.id}-panel-${id}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-hero-case="${id}">${cases[id].session.title}</button>`).join("")}</div>${v.hero.map((id,i)=>`<div class="memory-panel" role="tabpanel" id="${v.id}-panel-${id}" aria-labelledby="${v.id}-tab-${id}" ${i?"hidden":""}>${["tg","max"].map((provider,j)=>`<div class="dialogue-provider" data-dialogue-provider="${provider}" ${j?"hidden":""}>${originalDialogue(v,id,provider)}</div>`).join("")}<div class="demo-bottom"><span>${v.mode==="answer"?"Original result, with its conversation history":v.mode==="walkthrough"?"Follow the requests and responses from the current landing":"Requests, tool calls and replies from the current landing"}</span><a href="/examples?case=${id}">Full walkthrough${icon.arrow}</a></div></div>`).join("")}</section>`
}
const rows = {
  outcomes: [
    ["search","Find information buried in chats","Recover recommendations, agreements and files without opening every conversation.",'<p><b>Example:</b> compare SQL courses people recommended and check whether the reviews mention exercises and feedback.</p>',"search"],
    ["note","Prepare for the conversation","Bring decisions, blockers and open questions into a brief before a meeting.",'<p><b>Example:</b> a 20-minute project agenda built from the team group, design chat and DMs.</p>',"context"],
    ["reply","Reply with the history in mind","Check what arrived and what is still missing before following up.",'<blockquote>“Thanks for the first draft. When can you send the final version?”</blockquote>',"commitments"],
  ],
  roles: [
    ["account","Your personal account","Catch up on messages, find past agreements and draft replies from your own account.",'<p><b>What you get:</b> a short briefing, a source-backed answer or a reply ready to review.</p>',"inbox"],
    ["bot","Your customer-support bots","Ask your agent to prepare answers from the messages and knowledge you give it.",'<blockquote>“Friday is confirmed. I’ll check whether we can move delivery to tomorrow.”</blockquote>',"bot"],
    ["group","Groups you manage","Find unanswered questions, summarize discussions and preview moderation actions.",'<p><b>What you get:</b> the violations, the affected messages and a proposed action plan.</p>',"moderation"],
  ],
  workflow: [
    ["search","Find the right information","Ask for a recommendation, a document or a decision. Your agent gathers matching messages.",'<p><b>Found:</b> two SQL course recommendations, from Telegram and MAX.</p>',"search"],
    ["verify","Check what was actually said","Read the original messages and surrounding discussion before accepting a conclusion.",'<blockquote>“Weekly exercises and feedback from the instructor.”</blockquote>',"search"],
    ["reply","Turn it into an answer or action","Use the checked context to prepare a reply, a meeting brief or a note.",'<p><b>Result:</b> a comparison, a proposed next step, and the messages behind it.</p>',"commitments"],
  ],
}
function what(v) {
  return `<section class="wrap section what"><div class="what-intro"><h2>What you can do</h2><p>${v.type==='roles'?'Use your own account, work through a bot or manage a community. Choose the work you want your agent to handle.':'Ask your agent to find the information, check the history and help with the next step.'}</p></div><div class="what-columns">${rows[v.type].map(([ico,title,text,example,id])=>`<article>${icon[ico]}<h3>${title}</h3><p>${text}</p><div class="small-result">${example}</div>${link("See the example",`/examples?case=${id}`)}</article>`).join("")}</div></section>`
}
function roleBand(v) {
  if(v.type==='roles')return ""
  return `<section class="audience-band"><div class="wrap audience-row"><h2>Use your account,<br>bots and groups</h2><article><h3>Your account</h3><p>Catch up, find information and reply to your existing conversations.</p>${link("Personal account guide",`${docs}/tg/usage`)}</article><article><h3>Your bots</h3><p>Answer customers and send updates with your agent’s help.</p>${link("Bot guide",`${docs}/bot-api`)}</article><article><h3>Your groups</h3><p>Review unanswered questions and apply the rules you choose.</p>${link("Group guide",`${docs}/tg/groups`)}</article></div></section>`
}
function more(v) {
  const ids=v.type==='roles'?['inbox','files','schedule']:['files','moderation','bot']
  return `<section class="wrap section more-examples"><div class="section-title"><h2>${v.type==='roles'?'More tasks for your own account':'More ways to use your agent'}</h2><p>These are adapted from the current landing’s worked examples. Open a walkthrough to see the requests, tool calls and source messages.</p></div><div class="more-columns">${ids.map(id=>`<article><h3>${cases[id].title}</h3><p>${cases[id].caption}</p>${link("Open the walkthrough",`/examples?case=${id}`)}</article>`).join("")}</div></section>`
}
const tools = () => `<section class="wrap section integrations"><div><h2>Connect your messaging,<br>email and notes</h2><p>Start with the tools you use. Telegram and MAX are WireCat’s messaging tools. Email through Himalaya and your Obsidian vault can join the same agent workflow.</p><p class="project-definition">More messenger connections are planned. You can use today’s tools on their own.</p></div><div class="integration-table"><a href="${docs}/tg"><span>${icon.telegram}Telegram</span><p>tg · your account, bots and groups</p>${icon.arrow}</a><a href="${docs}/max"><span>${icon.max}MAX</span><p>max · your account, bots and groups</p>${icon.arrow}</a><a href="https://github.com/pimalaya/himalaya"><span>${icon.email}Email</span><p>Through the Himalaya CLI</p>${icon.arrow}</a><a href="https://obsidian.md"><span>${icon.note}Obsidian</span><p>Your notes, read and updated by your agent</p>${icon.arrow}</a><details><summary>How does this fit together?</summary><p>Your agent coordinates the tools you connect. WireCat supplies the messaging tools; Himalaya is a separate open-source email tool; Obsidian is your existing vault.</p><p>For example, ask your agent to collect a discussion, check the latest email and prepare an update to your project note.</p></details></div></section>`
const why = () => `<section class="why-band"><div class="wrap"><div class="section-title"><h2>Why it works this well</h2><p>Practical features that help your agent handle the work you normally do in chat apps.</p></div><dl class="why-grid"><div><dt>Search stored history offline</dt><dd>Look through the archive on your computer without fetching every message again.</dd></div><div><dt>Keep work and personal accounts separate</dt><dd>Use profiles for different accounts and bots. Choose which ones a task should use.</dd></div><div><dt>Read voice notes as text</dt><dd>Get a transcript, then ask your agent to pick out the questions and next steps.</dd></div><div><dt>Send messages at the right time</dt><dd>Schedule reminders and follow-ups. Telegram delivers them even when your laptop is off.</dd></div><div><dt>Search words or conversation meaning</dt><dd>Use exact message filters, or build and embed conversations for semantic retrieval.</dd></div><div><dt>Check what was sent</dt><dd>Review send attempts in the journal. Record command runs when you need to inspect a task.</dd></div></dl>${link("See the full feature list",`${docs}/features`)}</div></section>`
const proof = () => `<section class="wrap trust useful-extras"><article>${icon.note}<div><h3>Get a digest of the channels you follow</h3><p>Ask your agent to pick out updates on the topics you care about, with links to the posts.</p>${link("See the morning briefing","/examples?case=inbox")}</div></article><article>${icon.search}<div><h3>Collect the latest files from different chats</h3><p>Find the current contract, invoices and presentation across groups and DMs. Keep older versions in the history.</p>${link("See the document example","/examples?case=files")}</div></article><article>${icon.group}<div><h3>Find questions that still need an answer</h3><p>Ask your agent to review a group for open questions so you can see where someone is waiting for help.</p>${link("Group review guide",`${docs}/tg/groups`)}</div></article></section>`
const calculator = () => `<section class="wrap section calculator"><div><h2>How much time could you get back?</h2><p>Compare your daily chat work with an agent-assisted workflow. Change the volume and the assumptions to match your day.</p><p class="micro">This is an estimate, not a measured speed or accuracy claim. Setup and history downloads are excluded.</p></div><div class="calculator-body"><div class="calculator-inputs">${[['messages','Messages per day',200,1000,10],['chats','Active chats per day',12,50,1],['replies','Replies per day',6,50,1]].map(([id,label,value,max,step])=>`<label for="calc-${id}">${label}<output data-volume="${id}">${value}</output></label><input id="calc-${id}" data-calc="${id}" type="range" min="0" max="${max}" step="${step}" value="${value}">`).join("")}<details><summary>Edit the time assumptions</summary>${[['readSeconds','Read a message manually, seconds',4],['contextSeconds','Find context per chat, seconds',45],['writeMinutes','Write a reply manually, minutes',3],['summaryMinutes','Read the daily briefing, minutes',8],['checkContextSeconds','Check context per chat, seconds',15],['checkReplyMinutes','Review a reply draft, minutes',1]].map(([id,label,value])=>`<label for="time-${id}">${label}<input id="time-${id}" data-timing="${id}" type="number" min="0" step="0.5" value="${value}"></label>`).join("")}</details></div><div class="calculator-result" aria-live="polite"><span id="saving-label">Time you could free up</span><p><strong id="saved-minutes">23</strong> minutes a day</p><p><b id="saved-monthly">9</b> hours over 22 working days</p><div><span>Manual work <b id="manual-time">40</b> min</span><span>With your agent <b id="agent-time">17</b> min</span></div><small>Based on the volumes and timings you entered.</small></div></div></section>`
const setup = () => `<section class="wrap section setup"><div><h2>Give your agent somewhere useful to start.</h2><p>Connect Telegram or MAX, then ask a question about a conversation you already have. Add email and notes when you want them in the same workflow.</p><div class="setup-actions">${connect("closing","Connect your agent")}${link("Installation guide",`${docs}/installation`)}</div><p class="micro">Free tools. Your existing agent or model may have its own costs.</p></div><div class="starter"><h3>Try a first question</h3><p>“Find a decision from last week and show me the messages behind it.”</p><button class="text-link" data-copy="Use tg cli to find a decision from last week and show me the messages behind it. Read only for this task.">Copy the request${icon.copy}</button><details><summary>Where is my information processed?</summary><p>The messaging archive is stored on your computer. Content given to your agent follows its local or cloud model configuration. Email and notes keep their own storage and access settings.</p></details></div></section>`
function footer() {
  let html=landing.footerHtml
  const contacts=`<ul class="foot-contacts"><li><a href="mailto:${esc(site.contacts.email)}">${esc(site.contacts.email)}</a></li><li><a href="${esc(site.contacts.telegram)}">Telegram · @${esc(new URL(site.contacts.telegram).pathname.slice(1))}</a></li></ul>`
  const command=html.match(/<span class="cmd">[\s\S]*?<\/span>/)?.[0]
  html=html.replace(/(<div class="foot-brand">[\s\S]*?<\/p>)/,b=>b+contacts).replace(/<a class="mark"[^>]*>[\s\S]*?<\/a>/,`<a class="wirecat-brand" href="https://wirecat.dev/en"><span class="wirecat-logo" role="img" aria-label="WireCat">${wirecatLogoSvg}</span></a>`)
  if(command)html=html.replace(command,"").replace('<div class="foot-bottom">',`<div class="footer-install"><span class="footer-install-label">Telegram · CLI + agent skill</span>${command}</div><div class="foot-bottom">`)
  html=html.replace(/href="\/(?!\/)([^"]*)"/g,'href="https://wirecat.dev/$1"')
  return `<div class="wirecat-landing footer-host"><div class="site-footer-shell site-footer-landing">${html}</div></div><div class="toast" role="status" aria-live="polite"></div>`
}
const doc = (title,body,palette="classic") => `<!doctype html><html lang="en" class="light" data-palette="${palette}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${title} · WireCat Memory variants</title><link rel="icon" href="/icon.svg"><link rel="stylesheet" href="/production-landing.css"><link rel="stylesheet" href="/production-theme.css"><link rel="stylesheet" href="/production-footer.css"><link rel="stylesheet" href="/base.css"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/refinement.css"><script src="/interactions.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a>${body}</body></html>`
await mkdir(new URL('previews/',root),{recursive:true})
for(const v of config)await writeFile(new URL(`${v.id}.html`,root),doc(v.name,`${header(v)}<main id="main">${colorControls()}${hero(v)}${what(v)}${roleBand(v)}${more(v)}${tools()}${why()}${proof()}${v.calculator?calculator():""}${setup()}</main>${footer()}`,v.palette))
const gallery=`${header()}<main class="wrap gallery" id="main"><h1>Memory.<br><em>Three ways to show your agent at work.</em></h1><p class="lede">The selected Outcomes page and purple/green colors, with Telegram, MAX and Email in the hero. Compare three presentations of the original landing conversations.</p><div class="memory-gallery">${config.map(v=>`<article><a class="preview-window" href="/${v.id}"><img src="/previews/${v.id}.png" alt="${v.name} preview" width="1440" height="1000"></a><h2>${v.name}</h2><p>${v.desc}</p>${link("Open this variant",`/${v.id}`)}</article>`).join("")}</div><div class="archive-links"><h2>Examples and previous designs</h2>${link("All eight landing scenarios","/examples")}${link("The three compact previous designs","http://127.0.0.1:4326/")}${link("The three original mockups","http://127.0.0.1:4326/references")}${link("The earlier six variants","http://127.0.0.1:4325/")}</div></main>${footer()}`
await writeFile(new URL('index.html',root),doc('Three hero variants',gallery))
const examples=`${header()}<main class="wrap examples-page" id="main"><h1>See the tasks<br><em>your agent can handle.</em></h1><p class="lede">The full worked examples from the current landing: requests, tool calls, results and source messages. The homepages show shorter versions of selected scenarios.</p><div class="walkthrough-tabs" role="tablist" aria-label="Choose a landing scenario">${Object.values(cases).map((c,i)=>`<button role="tab" type="button" id="walk-tab-${c.id}" aria-controls="walk-panel-${c.id}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-walkthrough="${c.id}">${c.title}</button>`).join("")}</div>${Object.values(cases).map((c,i)=>`<section class="walkthrough-panel" role="tabpanel" id="walk-panel-${c.id}" aria-labelledby="walk-tab-${c.id}" ${i?'hidden':''}><h2>${c.session.title}</h2><div class="walkthrough">${exchanges(c.session).map((part,i)=>renderExchange(part,`walk-${c.id}-${i}`)).join("")}</div></section>`).join("")}</main>${footer()}`
await writeFile(new URL('examples.html',root),doc('All landing scenarios',examples))
await writeFile(new URL('setup-prompts.js',root),`window.wirecatSetupPrompts=${JSON.stringify(Object.fromEntries(['tg','max'].map(t=>[t,wordsFor('en').onboarding.prompt(t,`@leemour/${t}-cli`)])))};`)
for(const filename of ['index.html','examples.html',...config.map(v=>`${v.id}.html`)]){const p=new URL(filename,root);const text=await readFile(p,'utf8');await writeFile(p,text.replace('<script src="/interactions.js"','<script src="/setup-prompts.js" defer></script><script src="/interactions.js"'))}
console.log('Built three original-conversation hero variants.')
